// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3AccountmanagementRemoveMemberModuleRequest struct {
	// The ID of a Censys organization. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
	// The ID of a Censys user. You can obtain a user's ID by listing users in an organization.
	UserID string `pathParam:"style=simple,explode=false,name=user_id"`
	// The module identifier, for example platform-search.
	Module string `pathParam:"style=simple,explode=false,name=module"`
}

func (v *V3AccountmanagementRemoveMemberModuleRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V3AccountmanagementRemoveMemberModuleRequest) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}

func (v *V3AccountmanagementRemoveMemberModuleRequest) GetModule() string {
	if v == nil {
		return ""
	}
	return v.Module
}

// #region class-body-v3accountmanagementremovemembermodulerequest
// #endregion class-body-v3accountmanagementremovemembermodulerequest

type V3AccountmanagementRemoveMemberModuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (v *V3AccountmanagementRemoveMemberModuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3AccountmanagementRemoveMemberModuleResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v3accountmanagementremovemembermoduleresponse
// #endregion class-body-v3accountmanagementremovemembermoduleresponse
