// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3AccountmanagementOrgCreditsUsageRequest struct {
	// The ID of a Censys organization. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
	// The date for the credit usage report in YYYY-MM-DD format (e.g., 2025-11-06).
	Date string `queryParam:"style=form,explode=false,name=date"`
}

func (v *V3AccountmanagementOrgCreditsUsageRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V3AccountmanagementOrgCreditsUsageRequest) GetDate() string {
	if v == nil {
		return ""
	}
	return v.Date
}

type V3AccountmanagementOrgCreditsUsageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ResponseEnvelopeCreditUsageReport *components.ResponseEnvelopeCreditUsageReport
	Headers                           map[string][]string
}

func (v *V3AccountmanagementOrgCreditsUsageResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3AccountmanagementOrgCreditsUsageResponse) GetResponseEnvelopeCreditUsageReport() *components.ResponseEnvelopeCreditUsageReport {
	if v == nil {
		return nil
	}
	return v.ResponseEnvelopeCreditUsageReport
}

func (v *V3AccountmanagementOrgCreditsUsageResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
