// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
	"io"
)

type V3GlobaldataAssetCertificateRawGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (o *V3GlobaldataAssetCertificateRawGlobals) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type V3GlobaldataAssetCertificateRawRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-set-your-organization-id) for more information.
	OrganizationID *string `queryParam:"style=form,explode=false,name=organization_id"`
	// The SHA-256 certificate fingerprint.
	CertificateID string `pathParam:"style=simple,explode=false,name=certificate_id"`
}

func (o *V3GlobaldataAssetCertificateRawRequest) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *V3GlobaldataAssetCertificateRawRequest) GetCertificateID() string {
	if o == nil {
		return ""
	}
	return o.CertificateID
}

type V3GlobaldataAssetCertificateRawResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
	Headers        map[string][]string
}

func (o *V3GlobaldataAssetCertificateRawResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3GlobaldataAssetCertificateRawResponse) GetResponseStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.ResponseStream
}

func (o *V3GlobaldataAssetCertificateRawResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
