// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3GlobaldataAssetWebpropertyListPostGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (o *V3GlobaldataAssetWebpropertyListPostGlobals) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type V3GlobaldataAssetWebpropertyListPostRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-set-your-organization-id) for more information.
	OrganizationID                *string                                  `queryParam:"style=form,explode=false,name=organization_id"`
	AssetWebpropertyListInputBody components.AssetWebpropertyListInputBody `request:"mediaType=application/json"`
}

func (o *V3GlobaldataAssetWebpropertyListPostRequest) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *V3GlobaldataAssetWebpropertyListPostRequest) GetAssetWebpropertyListInputBody() components.AssetWebpropertyListInputBody {
	if o == nil {
		return components.AssetWebpropertyListInputBody{}
	}
	return o.AssetWebpropertyListInputBody
}

type V3GlobaldataAssetWebpropertyListPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ResponseEnvelopeListWebpropertyAsset *components.ResponseEnvelopeListWebpropertyAsset
	Headers                              map[string][]string
}

func (o *V3GlobaldataAssetWebpropertyListPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3GlobaldataAssetWebpropertyListPostResponse) GetResponseEnvelopeListWebpropertyAsset() *components.ResponseEnvelopeListWebpropertyAsset {
	if o == nil {
		return nil
	}
	return o.ResponseEnvelopeListWebpropertyAsset
}

func (o *V3GlobaldataAssetWebpropertyListPostResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
