// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3GlobaldataAssetCertificateListRawPostGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (o *V3GlobaldataAssetCertificateListRawPostGlobals) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type V3GlobaldataAssetCertificateListRawPostRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-set-your-organization-id) for more information.
	OrganizationID                *string                                  `queryParam:"style=form,explode=false,name=organization_id"`
	AssetCertificateListInputBody components.AssetCertificateListInputBody `request:"mediaType=application/json"`
}

func (o *V3GlobaldataAssetCertificateListRawPostRequest) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *V3GlobaldataAssetCertificateListRawPostRequest) GetAssetCertificateListInputBody() components.AssetCertificateListInputBody {
	if o == nil {
		return components.AssetCertificateListInputBody{}
	}
	return o.AssetCertificateListInputBody
}

type V3GlobaldataAssetCertificateListRawPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ResponseEnvelopeListRawCertificateResponse *components.ResponseEnvelopeListRawCertificateResponse
	Headers                                    map[string][]string
}

func (o *V3GlobaldataAssetCertificateListRawPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3GlobaldataAssetCertificateListRawPostResponse) GetResponseEnvelopeListRawCertificateResponse() *components.ResponseEnvelopeListRawCertificateResponse {
	if o == nil {
		return nil
	}
	return o.ResponseEnvelopeListRawCertificateResponse
}

func (o *V3GlobaldataAssetCertificateListRawPostResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
