// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3GlobaldataAssetCertificateListRawGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (o *V3GlobaldataAssetCertificateListRawGlobals) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type V3GlobaldataAssetCertificateListRawRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-set-your-organization-id) for more information.
	OrganizationID *string `queryParam:"style=form,explode=false,name=organization_id"`
	// A list of SHA-256 certificate fingerprints.
	CertificateIds []string `queryParam:"style=form,explode=false,name=certificate_ids"`
}

func (o *V3GlobaldataAssetCertificateListRawRequest) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *V3GlobaldataAssetCertificateListRawRequest) GetCertificateIds() []string {
	if o == nil {
		return nil
	}
	return o.CertificateIds
}

type V3GlobaldataAssetCertificateListRawResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ResponseEnvelopeListRawCertificateResponse *components.ResponseEnvelopeListRawCertificateResponse
	Headers                                    map[string][]string
}

func (o *V3GlobaldataAssetCertificateListRawResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3GlobaldataAssetCertificateListRawResponse) GetResponseEnvelopeListRawCertificateResponse() *components.ResponseEnvelopeListRawCertificateResponse {
	if o == nil {
		return nil
	}
	return o.ResponseEnvelopeListRawCertificateResponse
}

func (o *V3GlobaldataAssetCertificateListRawResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
