// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3GlobaldataSearchConvertGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (o *V3GlobaldataSearchConvertGlobals) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type V3GlobaldataSearchConvertRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-set-your-organization-id) for more information.
	OrganizationID              *string                                `queryParam:"style=form,explode=false,name=organization_id"`
	SearchConvertQueryInputBody components.SearchConvertQueryInputBody `request:"mediaType=application/json"`
}

func (o *V3GlobaldataSearchConvertRequest) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *V3GlobaldataSearchConvertRequest) GetSearchConvertQueryInputBody() components.SearchConvertQueryInputBody {
	if o == nil {
		return components.SearchConvertQueryInputBody{}
	}
	return o.SearchConvertQueryInputBody
}

type V3GlobaldataSearchConvertResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ResponseEnvelopeListSearchConvertQueryResponse *components.ResponseEnvelopeListSearchConvertQueryResponse
	Headers                                        map[string][]string
}

func (o *V3GlobaldataSearchConvertResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3GlobaldataSearchConvertResponse) GetResponseEnvelopeListSearchConvertQueryResponse() *components.ResponseEnvelopeListSearchConvertQueryResponse {
	if o == nil {
		return nil
	}
	return o.ResponseEnvelopeListSearchConvertQueryResponse
}

func (o *V3GlobaldataSearchConvertResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
