// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3GlobaldataAssetHostListPostGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (o *V3GlobaldataAssetHostListPostGlobals) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

type V3GlobaldataAssetHostListPostRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-set-your-organization-id) for more information.
	OrganizationID         *string                           `queryParam:"style=form,explode=false,name=organization_id"`
	AssetHostListInputBody components.AssetHostListInputBody `request:"mediaType=application/json"`
}

func (o *V3GlobaldataAssetHostListPostRequest) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *V3GlobaldataAssetHostListPostRequest) GetAssetHostListInputBody() components.AssetHostListInputBody {
	if o == nil {
		return components.AssetHostListInputBody{}
	}
	return o.AssetHostListInputBody
}

type V3GlobaldataAssetHostListPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ResponseEnvelopeListHostAsset *components.ResponseEnvelopeListHostAsset
	Headers                       map[string][]string
}

func (o *V3GlobaldataAssetHostListPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3GlobaldataAssetHostListPostResponse) GetResponseEnvelopeListHostAsset() *components.ResponseEnvelopeListHostAsset {
	if o == nil {
		return nil
	}
	return o.ResponseEnvelopeListHostAsset
}

func (o *V3GlobaldataAssetHostListPostResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
