// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3ThreathuntingInvestigationsFilesCreateGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (v *V3ThreathuntingInvestigationsFilesCreateGlobals) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

// #region class-body-v3threathuntinginvestigationsfilescreateglobals
// #endregion class-body-v3threathuntinginvestigationsfilescreateglobals

type V3ThreathuntingInvestigationsFilesCreateRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
	OrganizationID                   *string                                     `queryParam:"style=form,explode=false,name=organization_id"`
	CreateInvestigationFileInputBody components.CreateInvestigationFileInputBody `request:"mediaType=application/json"`
}

func (v *V3ThreathuntingInvestigationsFilesCreateRequest) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

func (v *V3ThreathuntingInvestigationsFilesCreateRequest) GetCreateInvestigationFileInputBody() components.CreateInvestigationFileInputBody {
	if v == nil {
		return components.CreateInvestigationFileInputBody{}
	}
	return v.CreateInvestigationFileInputBody
}

// #region class-body-v3threathuntinginvestigationsfilescreaterequest
// #endregion class-body-v3threathuntinginvestigationsfilescreaterequest

type V3ThreathuntingInvestigationsFilesCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Upload prepared successfully
	ResponseEnvelopeInvestigationFileUpload *components.ResponseEnvelopeInvestigationFileUpload
	Headers                                 map[string][]string
}

func (v *V3ThreathuntingInvestigationsFilesCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3ThreathuntingInvestigationsFilesCreateResponse) GetResponseEnvelopeInvestigationFileUpload() *components.ResponseEnvelopeInvestigationFileUpload {
	if v == nil {
		return nil
	}
	return v.ResponseEnvelopeInvestigationFileUpload
}

func (v *V3ThreathuntingInvestigationsFilesCreateResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v3threathuntinginvestigationsfilescreateresponse
// #endregion class-body-v3threathuntinginvestigationsfilescreateresponse
