// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3ThreathuntingInvestigationsJobsCreateGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (v *V3ThreathuntingInvestigationsJobsCreateGlobals) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

// #region class-body-v3threathuntinginvestigationsjobscreateglobals
// #endregion class-body-v3threathuntinginvestigationsjobscreateglobals

type V3ThreathuntingInvestigationsJobsCreateRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
	OrganizationID                  *string                                    `queryParam:"style=form,explode=false,name=organization_id"`
	CreateInvestigationJobInputBody components.CreateInvestigationJobInputBody `request:"mediaType=application/json"`
}

func (v *V3ThreathuntingInvestigationsJobsCreateRequest) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

func (v *V3ThreathuntingInvestigationsJobsCreateRequest) GetCreateInvestigationJobInputBody() components.CreateInvestigationJobInputBody {
	if v == nil {
		return components.CreateInvestigationJobInputBody{}
	}
	return v.CreateInvestigationJobInputBody
}

// #region class-body-v3threathuntinginvestigationsjobscreaterequest
// #endregion class-body-v3threathuntinginvestigationsjobscreaterequest

type V3ThreathuntingInvestigationsJobsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Investigation started successfully
	ResponseEnvelopeCreatedInvestigationJob *components.ResponseEnvelopeCreatedInvestigationJob
	Headers                                 map[string][]string
}

func (v *V3ThreathuntingInvestigationsJobsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3ThreathuntingInvestigationsJobsCreateResponse) GetResponseEnvelopeCreatedInvestigationJob() *components.ResponseEnvelopeCreatedInvestigationJob {
	if v == nil {
		return nil
	}
	return v.ResponseEnvelopeCreatedInvestigationJob
}

func (v *V3ThreathuntingInvestigationsJobsCreateResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v3threathuntinginvestigationsjobscreateresponse
// #endregion class-body-v3threathuntinginvestigationsjobscreateresponse
