// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/internal/utils"
	"github.com/censys/censys-sdk-go/models/components"
)

type V3ThreathuntingInvestigationsJobsListGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (v *V3ThreathuntingInvestigationsJobsListGlobals) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

// #region class-body-v3threathuntinginvestigationsjobslistglobals
// #endregion class-body-v3threathuntinginvestigationsjobslistglobals

type V3ThreathuntingInvestigationsJobsListRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
	OrganizationID *string `queryParam:"style=form,explode=false,name=organization_id"`
	// Number of investigations to return per page. Zero or omitted returns at most 50; values above 200 are reduced to 200.
	PageSize *int `default:"50" queryParam:"style=form,explode=false,name=page_size"`
	// Pagination token from the next_page_token of a previous response. Omit it to start from the first page.
	PageToken *string `queryParam:"style=form,explode=false,name=page_token"`
}

func (v V3ThreathuntingInvestigationsJobsListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ThreathuntingInvestigationsJobsListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3ThreathuntingInvestigationsJobsListRequest) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

func (v *V3ThreathuntingInvestigationsJobsListRequest) GetPageSize() *int {
	if v == nil {
		return nil
	}
	return v.PageSize
}

func (v *V3ThreathuntingInvestigationsJobsListRequest) GetPageToken() *string {
	if v == nil {
		return nil
	}
	return v.PageToken
}

// #region class-body-v3threathuntinginvestigationsjobslistrequest
// #endregion class-body-v3threathuntinginvestigationsjobslistrequest

type V3ThreathuntingInvestigationsJobsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Investigations retrieved successfully
	ResponseEnvelopeInvestigationJobsList *components.ResponseEnvelopeInvestigationJobsList
	Headers                               map[string][]string
}

func (v *V3ThreathuntingInvestigationsJobsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3ThreathuntingInvestigationsJobsListResponse) GetResponseEnvelopeInvestigationJobsList() *components.ResponseEnvelopeInvestigationJobsList {
	if v == nil {
		return nil
	}
	return v.ResponseEnvelopeInvestigationJobsList
}

func (v *V3ThreathuntingInvestigationsJobsListResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v3threathuntinginvestigationsjobslistresponse
// #endregion class-body-v3threathuntinginvestigationsjobslistresponse
