// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3ThreathuntingInvestigationsUsageGetGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (v *V3ThreathuntingInvestigationsUsageGetGlobals) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

// #region class-body-v3threathuntinginvestigationsusagegetglobals
// #endregion class-body-v3threathuntinginvestigationsusagegetglobals

type V3ThreathuntingInvestigationsUsageGetRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
	OrganizationID *string `queryParam:"style=form,explode=false,name=organization_id"`
}

func (v *V3ThreathuntingInvestigationsUsageGetRequest) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

// #region class-body-v3threathuntinginvestigationsusagegetrequest
// #endregion class-body-v3threathuntinginvestigationsusagegetrequest

type V3ThreathuntingInvestigationsUsageGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Investigation usage retrieved successfully
	ResponseEnvelopeInvestigationUsage *components.ResponseEnvelopeInvestigationUsage
	Headers                            map[string][]string
}

func (v *V3ThreathuntingInvestigationsUsageGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3ThreathuntingInvestigationsUsageGetResponse) GetResponseEnvelopeInvestigationUsage() *components.ResponseEnvelopeInvestigationUsage {
	if v == nil {
		return nil
	}
	return v.ResponseEnvelopeInvestigationUsage
}

func (v *V3ThreathuntingInvestigationsUsageGetResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v3threathuntinginvestigationsusagegetresponse
// #endregion class-body-v3threathuntinginvestigationsusagegetresponse
