// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
)

type V3ThreathuntingInvestigationsJobsGetGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (v *V3ThreathuntingInvestigationsJobsGetGlobals) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

// #region class-body-v3threathuntinginvestigationsjobsgetglobals
// #endregion class-body-v3threathuntinginvestigationsjobsgetglobals

type V3ThreathuntingInvestigationsJobsGetRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
	OrganizationID *string `queryParam:"style=form,explode=false,name=organization_id"`
	// The unique identifier of the investigation.
	JobID string `pathParam:"style=simple,explode=false,name=job_id"`
}

func (v *V3ThreathuntingInvestigationsJobsGetRequest) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

func (v *V3ThreathuntingInvestigationsJobsGetRequest) GetJobID() string {
	if v == nil {
		return ""
	}
	return v.JobID
}

// #region class-body-v3threathuntinginvestigationsjobsgetrequest
// #endregion class-body-v3threathuntinginvestigationsjobsgetrequest

type V3ThreathuntingInvestigationsJobsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Investigation retrieved successfully
	ResponseEnvelopeInvestigationJob *components.ResponseEnvelopeInvestigationJob
	Headers                          map[string][]string
}

func (v *V3ThreathuntingInvestigationsJobsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3ThreathuntingInvestigationsJobsGetResponse) GetResponseEnvelopeInvestigationJob() *components.ResponseEnvelopeInvestigationJob {
	if v == nil {
		return nil
	}
	return v.ResponseEnvelopeInvestigationJob
}

func (v *V3ThreathuntingInvestigationsJobsGetResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v3threathuntinginvestigationsjobsgetresponse
// #endregion class-body-v3threathuntinginvestigationsjobsgetresponse
