// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-sdk-go/models/components"
	"io"
)

type V3ThreathuntingInvestigationsJobsResultsGlobals struct {
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
}

func (v *V3ThreathuntingInvestigationsJobsResultsGlobals) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

// #region class-body-v3threathuntinginvestigationsjobsresultsglobals
// #endregion class-body-v3threathuntinginvestigationsjobsresultsglobals

type V3ThreathuntingInvestigationsJobsResultsRequest struct {
	// The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
	OrganizationID *string `queryParam:"style=form,explode=false,name=organization_id"`
	// The unique identifier of the investigation.
	JobID string `pathParam:"style=simple,explode=false,name=job_id"`
}

func (v *V3ThreathuntingInvestigationsJobsResultsRequest) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

func (v *V3ThreathuntingInvestigationsJobsResultsRequest) GetJobID() string {
	if v == nil {
		return ""
	}
	return v.JobID
}

// #region class-body-v3threathuntinginvestigationsjobsresultsrequest
// #endregion class-body-v3threathuntinginvestigationsjobsresultsrequest

type V3ThreathuntingInvestigationsJobsResultsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Investigation results archive
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
	Headers        map[string][]string
}

func (v *V3ThreathuntingInvestigationsJobsResultsResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3ThreathuntingInvestigationsJobsResultsResponse) GetResponseStream() io.ReadCloser {
	if v == nil {
		return nil
	}
	return v.ResponseStream
}

func (v *V3ThreathuntingInvestigationsJobsResultsResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v3threathuntinginvestigationsjobsresultsresponse
// #endregion class-body-v3threathuntinginvestigationsjobsresultsresponse
