// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Targets string

const (
	TargetsHost    Targets = "host"
	TargetsWeb     Targets = "web"
	TargetsCert    Targets = "cert"
	TargetsUnknown Targets = "unknown"
)

func (e Targets) ToPointer() *Targets {
	return &e
}
func (e *Targets) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "host":
		fallthrough
	case "web":
		fallthrough
	case "cert":
		fallthrough
	case "unknown":
		*e = Targets(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Targets: %v", v)
	}
}

type AlternativeQuery struct {
	// An alternative query that may be used.
	Query string `json:"query"`
	// The types of Platform data records (host, cert, and web) that can be targeted by the alternative query.
	Targets []Targets `json:"targets"`
}

func (a *AlternativeQuery) GetQuery() string {
	if a == nil {
		return ""
	}
	return a.Query
}

func (a *AlternativeQuery) GetTargets() []Targets {
	if a == nil {
		return nil
	}
	return a.Targets
}
