// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetCertificateListInputBody struct {
	// A list of SHA-256 certificate fingerprints.
	CertificateIds []string `json:"certificate_ids"`
}

func (o *AssetCertificateListInputBody) GetCertificateIds() []string {
	if o == nil {
		return nil
	}
	return o.CertificateIds
}
