// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetHostListInputBody struct {
	// A list of host IP addresses.
	HostIds []string `json:"host_ids"`
}

func (o *AssetHostListInputBody) GetHostIds() []string {
	if o == nil {
		return nil
	}
	return o.HostIds
}
