// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetWebpropertyListInputBody struct {
	// A list of web property identifiers.
	WebpropertyIds []string `json:"webproperty_ids"`
}

func (a *AssetWebpropertyListInputBody) GetWebpropertyIds() []string {
	if a == nil {
		return nil
	}
	return a.WebpropertyIds
}
