// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetHostListInputBody struct {
	// A list of host IP addresses.
	HostIds []string `json:"host_ids"`
}

func (a *AssetHostListInputBody) GetHostIds() []string {
	if a == nil {
		return nil
	}
	return a.HostIds
}
