// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetWebpropertyListInputBody struct {
	// A list of web property identifiers.
	WebpropertyIds []string `json:"webproperty_ids"`
}

func (o *AssetWebpropertyListInputBody) GetWebpropertyIds() []string {
	if o == nil {
		return nil
	}
	return o.WebpropertyIds
}
