// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Source string

const (
	SourceUnknown           Source = ""
	SourceCensys            Source = "censys"
	SourceRecog             Source = "recog"
	SourceWappalyzer        Source = "wappalyzer"
	SourceThirdParty        Source = "third_party"
	SourceHTMLMetaExtractor Source = "html_meta_extractor"
)

func (e Source) ToPointer() *Source {
	return &e
}
func (e *Source) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "censys":
		fallthrough
	case "recog":
		fallthrough
	case "wappalyzer":
		fallthrough
	case "third_party":
		fallthrough
	case "html_meta_extractor":
		*e = Source(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Source: %v", v)
	}
}

type Attribute struct {
	Components []Cpe         `json:"components,omitempty"`
	Confidence *float64      `json:"confidence,omitempty"`
	Cpe        *string       `json:"cpe,omitempty"`
	Edition    *string       `json:"edition,omitempty"`
	Evidence   []Evidence    `json:"evidence,omitempty"`
	LifeCycle  *CPELifeCycle `json:"life_cycle,omitempty"`
	Part       *string       `json:"part,omitempty"`
	Product    *string       `json:"product,omitempty"`
	Source     *Source       `json:"source,omitempty"`
	Type       []string      `json:"type,omitempty"`
	Update     *string       `json:"update,omitempty"`
	Vendor     *string       `json:"vendor,omitempty"`
	Version    *string       `json:"version,omitempty"`
}

func (a *Attribute) GetComponents() []Cpe {
	if a == nil {
		return nil
	}
	return a.Components
}

func (a *Attribute) GetConfidence() *float64 {
	if a == nil {
		return nil
	}
	return a.Confidence
}

func (a *Attribute) GetCpe() *string {
	if a == nil {
		return nil
	}
	return a.Cpe
}

func (a *Attribute) GetEdition() *string {
	if a == nil {
		return nil
	}
	return a.Edition
}

func (a *Attribute) GetEvidence() []Evidence {
	if a == nil {
		return nil
	}
	return a.Evidence
}

func (a *Attribute) GetLifeCycle() *CPELifeCycle {
	if a == nil {
		return nil
	}
	return a.LifeCycle
}

func (a *Attribute) GetPart() *string {
	if a == nil {
		return nil
	}
	return a.Part
}

func (a *Attribute) GetProduct() *string {
	if a == nil {
		return nil
	}
	return a.Product
}

func (a *Attribute) GetSource() *Source {
	if a == nil {
		return nil
	}
	return a.Source
}

func (a *Attribute) GetType() []string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *Attribute) GetUpdate() *string {
	if a == nil {
		return nil
	}
	return a.Update
}

func (a *Attribute) GetVendor() *string {
	if a == nil {
		return nil
	}
	return a.Vendor
}

func (a *Attribute) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}
