// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConvertQueryError struct {
	// The error message if the query could not be converted.
	Message string `json:"message"`
}

func (o *ConvertQueryError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
