// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CountCondition struct {
	// Field-value pairs to count matches for. Must target fields from the same nested object.
	FieldValuePairs []FieldValuePair `json:"field_value_pairs"`
}

func (c *CountCondition) GetFieldValuePairs() []FieldValuePair {
	if c == nil {
		return nil
	}
	return c.FieldValuePairs
}
