// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-sdk-go/internal/utils"
	"time"
)

// CreatedInvestigationJobState - The current state of the investigation. Completed means the investigation succeeded, not that its results are still available to download, and unknown means only that this API is older than the state the service reported.
type CreatedInvestigationJobState string

const (
	CreatedInvestigationJobStateStarted   CreatedInvestigationJobState = "started"
	CreatedInvestigationJobStateCompleted CreatedInvestigationJobState = "completed"
	CreatedInvestigationJobStateFailed    CreatedInvestigationJobState = "failed"
	CreatedInvestigationJobStateUnknown   CreatedInvestigationJobState = "unknown"
)

func (e CreatedInvestigationJobState) ToPointer() *CreatedInvestigationJobState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreatedInvestigationJobState) IsExact() bool {
	if e != nil {
		switch *e {
		case "started", "completed", "failed", "unknown":
			return true
		}
	}
	return false
}

type CreatedInvestigationJob struct {
	// When the investigation finished. Omitted while it is still running.
	CompleteTime *time.Time `json:"complete_time,omitempty"`
	// When the investigation was started.
	CreateTime time.Time `json:"create_time"`
	// End of the reported timeframe, echoed from the request that started it. Omitted when the request left it open, in which case the investigation was scoped up to the moment it started. The investigation does not store it, so it is returned only here and never by a later read.
	EndTime *time.Time `json:"end_time,omitempty"`
	// When the investigation and its results stop being available for download.
	ExpireTime *time.Time `json:"expire_time,omitempty"`
	// The unique identifier of the investigation.
	JobID string `json:"job_id"`
	// Start of the reported timeframe this investigation was scoped to, echoed from the request that started it. Omitted when the investigation uses current data. The investigation does not store it, so it is returned only here and never by a later read.
	StartTime *time.Time `json:"start_time,omitempty"`
	// The current state of the investigation. Completed means the investigation succeeded, not that its results are still available to download, and unknown means only that this API is older than the state the service reported.
	State CreatedInvestigationJobState `json:"state"`
	// A short description of what the investigation looked into. Omitted when the investigation has no title yet.
	Title *string `json:"title,omitempty"`
}

func (c CreatedInvestigationJob) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatedInvestigationJob) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatedInvestigationJob) GetCompleteTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.CompleteTime
}

func (c *CreatedInvestigationJob) GetCreateTime() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreateTime
}

func (c *CreatedInvestigationJob) GetEndTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndTime
}

func (c *CreatedInvestigationJob) GetExpireTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.ExpireTime
}

func (c *CreatedInvestigationJob) GetJobID() string {
	if c == nil {
		return ""
	}
	return c.JobID
}

func (c *CreatedInvestigationJob) GetStartTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartTime
}

func (c *CreatedInvestigationJob) GetState() CreatedInvestigationJobState {
	if c == nil {
		return CreatedInvestigationJobState("")
	}
	return c.State
}

func (c *CreatedInvestigationJob) GetTitle() *string {
	if c == nil {
		return nil
	}
	return c.Title
}
