// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-sdk-go/internal/utils"
	"time"
)

type CreateInvestigationJobInputBody struct {
	// End of the reported timeframe, as an RFC 3339 timestamp. Inclusive. Requires start_time and must not be before it. It may not be in the future; omit it to scope the investigation up to now. Equal bounds scope the investigation to that single instant.
	EndTime *time.Time `json:"end_time,omitempty"`
	// Evidence files to investigate, identified by the file_id returned when each upload was prepared. The most that one investigation accepts is set by the service and can change. A file is meant for one investigation. A later job naming the same file is rejected, though as with a retried create, two requests sent at the same instant may both be accepted. An identifier that was never uploaded, or that belongs to someone else, returns an unprocessable entity response. May be omitted when indicators is supplied.
	FileIds []string `json:"file_ids,omitempty"`
	// The indicators to investigate. Can be IP addresses, domains, or host and port pairs. Each must be a single non-empty value. May be omitted when file_ids is provided. The maximum number of indicators you can submit is 100.
	Indicators []string `json:"indicators,omitempty"`
	// Start of the reported timeframe to scope the investigation to, as an RFC 3339 timestamp. Inclusive, and must be in the past. Omit both start_time and end_time to investigate current data. Supplying start_time on its own scopes the investigation from that instant up to now, which is how an open-ended report is expressed.
	StartTime *time.Time `json:"start_time,omitempty"`
}

func (c CreateInvestigationJobInputBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInvestigationJobInputBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateInvestigationJobInputBody) GetEndTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndTime
}

func (c *CreateInvestigationJobInputBody) GetFileIds() []string {
	if c == nil {
		return nil
	}
	return c.FileIds
}

func (c *CreateInvestigationJobInputBody) GetIndicators() []string {
	if c == nil {
		return nil
	}
	return c.Indicators
}

func (c *CreateInvestigationJobInputBody) GetStartTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartTime
}
