// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ContentType - The media type of the file to upload. Send it bare: a type carrying parameters, such as a charset, is not accepted.
type ContentType string

const (
	ContentTypeApplicationPdf ContentType = "application/pdf"
	ContentTypeTextHTML       ContentType = "text/html"
	ContentTypeTextCsv        ContentType = "text/csv"
	ContentTypeTextPlain      ContentType = "text/plain"
	ContentTypeImagePng       ContentType = "image/png"
	ContentTypeImageJpeg      ContentType = "image/jpeg"
	ContentTypeImageWebp      ContentType = "image/webp"
)

func (e ContentType) ToPointer() *ContentType {
	return &e
}
func (e *ContentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "application/pdf":
		fallthrough
	case "text/html":
		fallthrough
	case "text/csv":
		fallthrough
	case "text/plain":
		fallthrough
	case "image/png":
		fallthrough
	case "image/jpeg":
		fallthrough
	case "image/webp":
		*e = ContentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContentType: %v", v)
	}
}

type CreateInvestigationFileInputBody struct {
	// The media type of the file to upload. Send it bare: a type carrying parameters, such as a charset, is not accepted.
	ContentType ContentType `json:"content_type"`
	// The original name of the file. Used only as display metadata on the investigation; it does not affect where the file is stored.
	Filename *string `json:"filename,omitempty"`
	// The size of the file in bytes. The largest a single file may be is set by the service and can change; sending more returns an unprocessable entity response. The upload itself is limited independently, so understating this does not raise the limit.
	SizeBytes int64 `json:"size_bytes"`
}

func (c *CreateInvestigationFileInputBody) GetContentType() ContentType {
	if c == nil {
		return ContentType("")
	}
	return c.ContentType
}

func (c *CreateInvestigationFileInputBody) GetFilename() *string {
	if c == nil {
		return nil
	}
	return c.Filename
}

func (c *CreateInvestigationFileInputBody) GetSizeBytes() int64 {
	if c == nil {
		return 0
	}
	return c.SizeBytes
}
