// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-sdk-go/internal/utils"
	"time"
)

type CreditUsageReport struct {
	// The end date of the window for this report.
	EndDate         time.Time            `json:"end_date"`
	SourceBreakdown SourceUsageBreakdown `json:"source_breakdown"`
	// The start date of the window for this report.
	StartDate time.Time `json:"start_date"`
	// The total amount of credits consumed during the report period.
	TotalConsumed int64 `json:"total_consumed"`
}

func (c CreditUsageReport) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditUsageReport) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditUsageReport) GetEndDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.EndDate
}

func (c *CreditUsageReport) GetSourceBreakdown() SourceUsageBreakdown {
	if c == nil {
		return SourceUsageBreakdown{}
	}
	return c.SourceBreakdown
}

func (c *CreditUsageReport) GetStartDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.StartDate
}

func (c *CreditUsageReport) GetTotalConsumed() int64 {
	if c == nil {
		return 0
	}
	return c.TotalConsumed
}
