// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ElasticSearchResultsNodeInfoClusterCombinedInfoFilesystem struct {
	Available        *string `json:"available,omitempty"`
	AvailableInBytes *int    `json:"available_in_bytes,omitempty"`
	Free             *string `json:"free,omitempty"`
	FreeInBytes      *int    `json:"free_in_bytes,omitempty"`
	Total            *string `json:"total,omitempty"`
	TotalInBytes     *int    `json:"total_in_bytes,omitempty"`
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoFilesystem) GetAvailable() *string {
	if e == nil {
		return nil
	}
	return e.Available
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoFilesystem) GetAvailableInBytes() *int {
	if e == nil {
		return nil
	}
	return e.AvailableInBytes
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoFilesystem) GetFree() *string {
	if e == nil {
		return nil
	}
	return e.Free
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoFilesystem) GetFreeInBytes() *int {
	if e == nil {
		return nil
	}
	return e.FreeInBytes
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoFilesystem) GetTotal() *string {
	if e == nil {
		return nil
	}
	return e.Total
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoFilesystem) GetTotalInBytes() *int {
	if e == nil {
		return nil
	}
	return e.TotalInBytes
}
