// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesStore struct {
	ReservedInBytes *int `json:"reserved_in_bytes,omitempty"`
	SizeInBytes     *int `json:"size_in_bytes,omitempty"`
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesStore) GetReservedInBytes() *int {
	if e == nil {
		return nil
	}
	return e.ReservedInBytes
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesStore) GetSizeInBytes() *int {
	if e == nil {
		return nil
	}
	return e.SizeInBytes
}
