// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesDocs struct {
	Count   *int `json:"count,omitempty"`
	Deleted *int `json:"deleted,omitempty"`
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesDocs) GetCount() *int {
	if e == nil {
		return nil
	}
	return e.Count
}

func (e *ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesDocs) GetDeleted() *int {
	if e == nil {
		return nil
	}
	return e.Deleted
}
