// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type EndpointScanTransportProtocol string

const (
	EndpointScanTransportProtocolUnknown EndpointScanTransportProtocol = ""
	EndpointScanTransportProtocolTCP     EndpointScanTransportProtocol = "tcp"
	EndpointScanTransportProtocolUDP     EndpointScanTransportProtocol = "udp"
	EndpointScanTransportProtocolIcmp    EndpointScanTransportProtocol = "icmp"
	EndpointScanTransportProtocolQuic    EndpointScanTransportProtocol = "quic"
)

func (e EndpointScanTransportProtocol) ToPointer() *EndpointScanTransportProtocol {
	return &e
}
func (e *EndpointScanTransportProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "tcp":
		fallthrough
	case "udp":
		fallthrough
	case "icmp":
		fallthrough
	case "quic":
		*e = EndpointScanTransportProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EndpointScanTransportProtocol: %v", v)
	}
}

type EndpointScan struct {
	Banner            *string                        `json:"banner,omitempty"`
	BannerHashSha256  *string                        `json:"banner_hash_sha256,omitempty"`
	ChromeDevtools    *ChromeDevtools                `json:"chrome_devtools,omitempty"`
	CobaltStrike      *CobaltStrike                  `json:"cobalt_strike,omitempty"`
	Elasticsearch     *ElasticSearch                 `json:"elasticsearch,omitempty"`
	EndpointType      *string                        `json:"endpoint_type,omitempty"`
	Fortigate         *Fortigate                     `json:"fortigate,omitempty"`
	Graphql           *Graphql                       `json:"graphql,omitempty"`
	Hostname          *string                        `json:"hostname,omitempty"`
	HTTP              *HTTP                          `json:"http,omitempty"`
	IP                *string                        `json:"ip,omitempty"`
	IsSuccess         *bool                          `json:"is_success,omitempty"`
	IvantiAvalanche   *IvantiAvalanche               `json:"ivanti_avalanche,omitempty"`
	Jenkins           *Jenkins                       `json:"jenkins,omitempty"`
	Kubernetes        *Kubernetes                    `json:"kubernetes,omitempty"`
	Ollama            *Ollama                        `json:"ollama,omitempty"`
	OpenDirectory     *OpenDirectory                 `json:"open_directory,omitempty"`
	Path              *string                        `json:"path,omitempty"`
	PlexMediaServer   *PlexMediaServer               `json:"plex_media_server,omitempty"`
	Port              *int                           `json:"port,omitempty"`
	Pprof             *Pprof                         `json:"pprof,omitempty"`
	Prometheus        *Prometheus                    `json:"prometheus,omitempty"`
	PrometheusTarget  *PrometheusTarget              `json:"prometheus_target,omitempty"`
	RedlionWeb        *RedlionWeb                    `json:"redlion_web,omitempty"`
	ScadaView         *ScadaView                     `json:"scada_view,omitempty"`
	ScanTime          *string                        `json:"scan_time,omitempty"`
	Screenshots       []Screenshot                   `json:"screenshots,omitempty"`
	TLS               *TLS                           `json:"tls,omitempty"`
	TransportProtocol *EndpointScanTransportProtocol `json:"transport_protocol,omitempty"`
}

func (e *EndpointScan) GetBanner() *string {
	if e == nil {
		return nil
	}
	return e.Banner
}

func (e *EndpointScan) GetBannerHashSha256() *string {
	if e == nil {
		return nil
	}
	return e.BannerHashSha256
}

func (e *EndpointScan) GetChromeDevtools() *ChromeDevtools {
	if e == nil {
		return nil
	}
	return e.ChromeDevtools
}

func (e *EndpointScan) GetCobaltStrike() *CobaltStrike {
	if e == nil {
		return nil
	}
	return e.CobaltStrike
}

func (e *EndpointScan) GetElasticsearch() *ElasticSearch {
	if e == nil {
		return nil
	}
	return e.Elasticsearch
}

func (e *EndpointScan) GetEndpointType() *string {
	if e == nil {
		return nil
	}
	return e.EndpointType
}

func (e *EndpointScan) GetFortigate() *Fortigate {
	if e == nil {
		return nil
	}
	return e.Fortigate
}

func (e *EndpointScan) GetGraphql() *Graphql {
	if e == nil {
		return nil
	}
	return e.Graphql
}

func (e *EndpointScan) GetHostname() *string {
	if e == nil {
		return nil
	}
	return e.Hostname
}

func (e *EndpointScan) GetHTTP() *HTTP {
	if e == nil {
		return nil
	}
	return e.HTTP
}

func (e *EndpointScan) GetIP() *string {
	if e == nil {
		return nil
	}
	return e.IP
}

func (e *EndpointScan) GetIsSuccess() *bool {
	if e == nil {
		return nil
	}
	return e.IsSuccess
}

func (e *EndpointScan) GetIvantiAvalanche() *IvantiAvalanche {
	if e == nil {
		return nil
	}
	return e.IvantiAvalanche
}

func (e *EndpointScan) GetJenkins() *Jenkins {
	if e == nil {
		return nil
	}
	return e.Jenkins
}

func (e *EndpointScan) GetKubernetes() *Kubernetes {
	if e == nil {
		return nil
	}
	return e.Kubernetes
}

func (e *EndpointScan) GetOllama() *Ollama {
	if e == nil {
		return nil
	}
	return e.Ollama
}

func (e *EndpointScan) GetOpenDirectory() *OpenDirectory {
	if e == nil {
		return nil
	}
	return e.OpenDirectory
}

func (e *EndpointScan) GetPath() *string {
	if e == nil {
		return nil
	}
	return e.Path
}

func (e *EndpointScan) GetPlexMediaServer() *PlexMediaServer {
	if e == nil {
		return nil
	}
	return e.PlexMediaServer
}

func (e *EndpointScan) GetPort() *int {
	if e == nil {
		return nil
	}
	return e.Port
}

func (e *EndpointScan) GetPprof() *Pprof {
	if e == nil {
		return nil
	}
	return e.Pprof
}

func (e *EndpointScan) GetPrometheus() *Prometheus {
	if e == nil {
		return nil
	}
	return e.Prometheus
}

func (e *EndpointScan) GetPrometheusTarget() *PrometheusTarget {
	if e == nil {
		return nil
	}
	return e.PrometheusTarget
}

func (e *EndpointScan) GetRedlionWeb() *RedlionWeb {
	if e == nil {
		return nil
	}
	return e.RedlionWeb
}

func (e *EndpointScan) GetScadaView() *ScadaView {
	if e == nil {
		return nil
	}
	return e.ScadaView
}

func (e *EndpointScan) GetScanTime() *string {
	if e == nil {
		return nil
	}
	return e.ScanTime
}

func (e *EndpointScan) GetScreenshots() []Screenshot {
	if e == nil {
		return nil
	}
	return e.Screenshots
}

func (e *EndpointScan) GetTLS() *TLS {
	if e == nil {
		return nil
	}
	return e.TLS
}

func (e *EndpointScan) GetTransportProtocol() *EndpointScanTransportProtocol {
	if e == nil {
		return nil
	}
	return e.TransportProtocol
}
