// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type EndpointScanStateTransportProtocol string

const (
	EndpointScanStateTransportProtocolUnknown EndpointScanStateTransportProtocol = ""
	EndpointScanStateTransportProtocolTCP     EndpointScanStateTransportProtocol = "tcp"
	EndpointScanStateTransportProtocolUDP     EndpointScanStateTransportProtocol = "udp"
	EndpointScanStateTransportProtocolIcmp    EndpointScanStateTransportProtocol = "icmp"
	EndpointScanStateTransportProtocolQuic    EndpointScanStateTransportProtocol = "quic"
)

func (e EndpointScanStateTransportProtocol) ToPointer() *EndpointScanStateTransportProtocol {
	return &e
}
func (e *EndpointScanStateTransportProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "tcp":
		fallthrough
	case "udp":
		fallthrough
	case "icmp":
		fallthrough
	case "quic":
		*e = EndpointScanStateTransportProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EndpointScanStateTransportProtocol: %v", v)
	}
}

type EndpointScanState struct {
	Banner            *string                             `json:"banner,omitempty"`
	BannerHashSha256  *string                             `json:"banner_hash_sha256,omitempty"`
	ChromeDevtools    *ChromeDevtools                     `json:"chrome_devtools,omitempty"`
	CobaltStrike      *CobaltStrike                       `json:"cobalt_strike,omitempty"`
	Elasticsearch     *ElasticSearch                      `json:"elasticsearch,omitempty"`
	EndpointType      *string                             `json:"endpoint_type,omitempty"`
	Fortigate         *Fortigate                          `json:"fortigate,omitempty"`
	Graphql           *Graphql                            `json:"graphql,omitempty"`
	Hostname          *string                             `json:"hostname,omitempty"`
	HTTP              *HTTP                               `json:"http,omitempty"`
	IP                *string                             `json:"ip,omitempty"`
	IvantiAvalanche   *IvantiAvalanche                    `json:"ivanti_avalanche,omitempty"`
	Kubernetes        *Kubernetes                         `json:"kubernetes,omitempty"`
	Ollama            *Ollama                             `json:"ollama,omitempty"`
	OpenDirectory     *OpenDirectory                      `json:"open_directory,omitempty"`
	Path              *string                             `json:"path,omitempty"`
	PlexMediaServer   *PlexMediaServer                    `json:"plex_media_server,omitempty"`
	Port              *int                                `json:"port,omitempty"`
	Pprof             *Pprof                              `json:"pprof,omitempty"`
	Prometheus        *Prometheus                         `json:"prometheus,omitempty"`
	PrometheusTarget  *PrometheusTarget                   `json:"prometheus_target,omitempty"`
	RedlionWeb        *RedlionWeb                         `json:"redlion_web,omitempty"`
	ScadaView         *ScadaView                          `json:"scada_view,omitempty"`
	ScanTime          *string                             `json:"scan_time,omitempty"`
	Screenshots       []Screenshot                        `json:"screenshots,omitempty"`
	TransportProtocol *EndpointScanStateTransportProtocol `json:"transport_protocol,omitempty"`
}

func (e *EndpointScanState) GetBanner() *string {
	if e == nil {
		return nil
	}
	return e.Banner
}

func (e *EndpointScanState) GetBannerHashSha256() *string {
	if e == nil {
		return nil
	}
	return e.BannerHashSha256
}

func (e *EndpointScanState) GetChromeDevtools() *ChromeDevtools {
	if e == nil {
		return nil
	}
	return e.ChromeDevtools
}

func (e *EndpointScanState) GetCobaltStrike() *CobaltStrike {
	if e == nil {
		return nil
	}
	return e.CobaltStrike
}

func (e *EndpointScanState) GetElasticsearch() *ElasticSearch {
	if e == nil {
		return nil
	}
	return e.Elasticsearch
}

func (e *EndpointScanState) GetEndpointType() *string {
	if e == nil {
		return nil
	}
	return e.EndpointType
}

func (e *EndpointScanState) GetFortigate() *Fortigate {
	if e == nil {
		return nil
	}
	return e.Fortigate
}

func (e *EndpointScanState) GetGraphql() *Graphql {
	if e == nil {
		return nil
	}
	return e.Graphql
}

func (e *EndpointScanState) GetHostname() *string {
	if e == nil {
		return nil
	}
	return e.Hostname
}

func (e *EndpointScanState) GetHTTP() *HTTP {
	if e == nil {
		return nil
	}
	return e.HTTP
}

func (e *EndpointScanState) GetIP() *string {
	if e == nil {
		return nil
	}
	return e.IP
}

func (e *EndpointScanState) GetIvantiAvalanche() *IvantiAvalanche {
	if e == nil {
		return nil
	}
	return e.IvantiAvalanche
}

func (e *EndpointScanState) GetKubernetes() *Kubernetes {
	if e == nil {
		return nil
	}
	return e.Kubernetes
}

func (e *EndpointScanState) GetOllama() *Ollama {
	if e == nil {
		return nil
	}
	return e.Ollama
}

func (e *EndpointScanState) GetOpenDirectory() *OpenDirectory {
	if e == nil {
		return nil
	}
	return e.OpenDirectory
}

func (e *EndpointScanState) GetPath() *string {
	if e == nil {
		return nil
	}
	return e.Path
}

func (e *EndpointScanState) GetPlexMediaServer() *PlexMediaServer {
	if e == nil {
		return nil
	}
	return e.PlexMediaServer
}

func (e *EndpointScanState) GetPort() *int {
	if e == nil {
		return nil
	}
	return e.Port
}

func (e *EndpointScanState) GetPprof() *Pprof {
	if e == nil {
		return nil
	}
	return e.Pprof
}

func (e *EndpointScanState) GetPrometheus() *Prometheus {
	if e == nil {
		return nil
	}
	return e.Prometheus
}

func (e *EndpointScanState) GetPrometheusTarget() *PrometheusTarget {
	if e == nil {
		return nil
	}
	return e.PrometheusTarget
}

func (e *EndpointScanState) GetRedlionWeb() *RedlionWeb {
	if e == nil {
		return nil
	}
	return e.RedlionWeb
}

func (e *EndpointScanState) GetScadaView() *ScadaView {
	if e == nil {
		return nil
	}
	return e.ScadaView
}

func (e *EndpointScanState) GetScanTime() *string {
	if e == nil {
		return nil
	}
	return e.ScanTime
}

func (e *EndpointScanState) GetScreenshots() []Screenshot {
	if e == nil {
		return nil
	}
	return e.Screenshots
}

func (e *EndpointScanState) GetTransportProtocol() *EndpointScanStateTransportProtocol {
	if e == nil {
		return nil
	}
	return e.TransportProtocol
}
