// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Greynoise struct {
	// The actor that was observed.
	Actor *string `json:"actor,omitempty"`
	// The classification of the IP address.
	Classification *string `json:"classification,omitempty"`
	// The tags associated with the IP address.
	Tags []GreynoiseTag `json:"tags,omitempty"`
}

func (g *Greynoise) GetActor() *string {
	if g == nil {
		return nil
	}
	return g.Actor
}

func (g *Greynoise) GetClassification() *string {
	if g == nil {
		return nil
	}
	return g.Classification
}

func (g *Greynoise) GetTags() []GreynoiseTag {
	if g == nil {
		return nil
	}
	return g.Tags
}
