// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type RecordType string

const (
	RecordTypeUnknown RecordType = ""
	RecordTypeA       RecordType = "a"
	RecordTypeAaaa    RecordType = "aaaa"
)

func (e RecordType) ToPointer() *RecordType {
	return &e
}
func (e *RecordType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "a":
		fallthrough
	case "aaaa":
		*e = RecordType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecordType: %v", v)
	}
}

type HostDNSForwardResolution struct {
	Name        *string     `json:"name,omitempty"`
	RecordType  *RecordType `json:"record_type,omitempty"`
	ResolveTime *string     `json:"resolve_time,omitempty"`
	Server      *string     `json:"server,omitempty"`
}

func (h *HostDNSForwardResolution) GetName() *string {
	if h == nil {
		return nil
	}
	return h.Name
}

func (h *HostDNSForwardResolution) GetRecordType() *RecordType {
	if h == nil {
		return nil
	}
	return h.RecordType
}

func (h *HostDNSForwardResolution) GetResolveTime() *string {
	if h == nil {
		return nil
	}
	return h.ResolveTime
}

func (h *HostDNSForwardResolution) GetServer() *string {
	if h == nil {
		return nil
	}
	return h.Server
}
