// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type HTTPRedirectChainLinkTransportProtocol string

const (
	HTTPRedirectChainLinkTransportProtocolUnknown HTTPRedirectChainLinkTransportProtocol = ""
	HTTPRedirectChainLinkTransportProtocolTCP     HTTPRedirectChainLinkTransportProtocol = "tcp"
	HTTPRedirectChainLinkTransportProtocolUDP     HTTPRedirectChainLinkTransportProtocol = "udp"
	HTTPRedirectChainLinkTransportProtocolIcmp    HTTPRedirectChainLinkTransportProtocol = "icmp"
	HTTPRedirectChainLinkTransportProtocolQuic    HTTPRedirectChainLinkTransportProtocol = "quic"
)

func (e HTTPRedirectChainLinkTransportProtocol) ToPointer() *HTTPRedirectChainLinkTransportProtocol {
	return &e
}
func (e *HTTPRedirectChainLinkTransportProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "tcp":
		fallthrough
	case "udp":
		fallthrough
	case "icmp":
		fallthrough
	case "quic":
		*e = HTTPRedirectChainLinkTransportProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for HTTPRedirectChainLinkTransportProtocol: %v", v)
	}
}

type HTTPRedirectChainLink struct {
	Hostname          *string                                 `json:"hostname,omitempty"`
	Path              *string                                 `json:"path,omitempty"`
	Port              *int                                    `json:"port,omitempty"`
	Reason            *string                                 `json:"reason,omitempty"`
	TransportProtocol *HTTPRedirectChainLinkTransportProtocol `json:"transport_protocol,omitempty"`
}

func (h *HTTPRedirectChainLink) GetHostname() *string {
	if h == nil {
		return nil
	}
	return h.Hostname
}

func (h *HTTPRedirectChainLink) GetPath() *string {
	if h == nil {
		return nil
	}
	return h.Path
}

func (h *HTTPRedirectChainLink) GetPort() *int {
	if h == nil {
		return nil
	}
	return h.Port
}

func (h *HTTPRedirectChainLink) GetReason() *string {
	if h == nil {
		return nil
	}
	return h.Reason
}

func (h *HTTPRedirectChainLink) GetTransportProtocol() *HTTPRedirectChainLinkTransportProtocol {
	if h == nil {
		return nil
	}
	return h.TransportProtocol
}
