// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InvestigationJobsList struct {
	// The caller's investigations in this organization, newest first.
	Jobs []InvestigationJob `json:"jobs"`
	// Token to retrieve the next page of investigations. Omitted when there are no more results.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

func (i *InvestigationJobsList) GetJobs() []InvestigationJob {
	if i == nil {
		return nil
	}
	return i.Jobs
}

func (i *InvestigationJobsList) GetNextPageToken() *string {
	if i == nil {
		return nil
	}
	return i.NextPageToken
}
