// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-sdk-go/internal/utils"
	"time"
)

type InvestigationUsage struct {
	// Maximum new investigations allowed per organization in the rolling window.
	Limit int64 `json:"limit"`
	// When the oldest counted start reaches the end of the rolling window and stops counting. This expires one start, it does not reset the allowance, and it is reported whenever any start is counted rather than only when remaining is zero. Omitted when used is zero.
	NextExpireTime *time.Time `json:"next_expire_time,omitempty"`
	// Additional new investigations available, never less than zero. This is a snapshot, not a reservation.
	Remaining int64 `json:"remaining"`
	// New investigations started by all organization members through the UI and API within the rolling window.
	Used int64 `json:"used"`
	// Duration of the rolling allowance window in seconds.
	WindowSeconds int64 `json:"window_seconds"`
}

func (i InvestigationUsage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InvestigationUsage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InvestigationUsage) GetLimit() int64 {
	if i == nil {
		return 0
	}
	return i.Limit
}

func (i *InvestigationUsage) GetNextExpireTime() *time.Time {
	if i == nil {
		return nil
	}
	return i.NextExpireTime
}

func (i *InvestigationUsage) GetRemaining() int64 {
	if i == nil {
		return 0
	}
	return i.Remaining
}

func (i *InvestigationUsage) GetUsed() int64 {
	if i == nil {
		return 0
	}
	return i.Used
}

func (i *InvestigationUsage) GetWindowSeconds() int64 {
	if i == nil {
		return 0
	}
	return i.WindowSeconds
}
