// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-sdk-go/internal/utils"
	"time"
)

type InvestigationFileUpload struct {
	// When upload_url stops working. A file that was uploaded before then stays usable afterwards; only the URL expires.
	ExpireTime time.Time `json:"expire_time"`
	// Identifier for the uploaded file, to be sent as a file_ids entry when starting an investigation. It is an opaque handle, not a storage location, and it is meant for one investigation.
	FileID string `json:"file_id"`
	// Send these headers on the PUT exactly as given. They are part of what the URL authorizes, so an upload that omits or changes one is rejected by storage.
	UploadHeaders map[string]string `json:"upload_headers"`
	// Send the file bytes here with an HTTP PUT. The URL grants access to this one file and nothing else, and stops working at expire_time.
	UploadURL string `json:"upload_url"`
}

func (i InvestigationFileUpload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InvestigationFileUpload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InvestigationFileUpload) GetExpireTime() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.ExpireTime
}

func (i *InvestigationFileUpload) GetFileID() string {
	if i == nil {
		return ""
	}
	return i.FileID
}

func (i *InvestigationFileUpload) GetUploadHeaders() map[string]string {
	if i == nil {
		return map[string]string{}
	}
	return i.UploadHeaders
}

func (i *InvestigationFileUpload) GetUploadURL() string {
	if i == nil {
		return ""
	}
	return i.UploadURL
}
