// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-sdk-go/internal/utils"
	"time"
)

// InvestigationJobState - The current state of the investigation. Completed means the investigation succeeded, not that its results are still available to download, and unknown means only that this API is older than the state the service reported.
type InvestigationJobState string

const (
	InvestigationJobStateStarted   InvestigationJobState = "started"
	InvestigationJobStateCompleted InvestigationJobState = "completed"
	InvestigationJobStateFailed    InvestigationJobState = "failed"
	InvestigationJobStateUnknown   InvestigationJobState = "unknown"
)

func (e InvestigationJobState) ToPointer() *InvestigationJobState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InvestigationJobState) IsExact() bool {
	if e != nil {
		switch *e {
		case "started", "completed", "failed", "unknown":
			return true
		}
	}
	return false
}

type InvestigationJob struct {
	// When the investigation finished. Omitted while it is still running.
	CompleteTime *time.Time `json:"complete_time,omitempty"`
	// When the investigation was started.
	CreateTime time.Time `json:"create_time"`
	// When the investigation and its results stop being available for download.
	ExpireTime *time.Time `json:"expire_time,omitempty"`
	// The unique identifier of the investigation.
	JobID string `json:"job_id"`
	// The current state of the investigation. Completed means the investigation succeeded, not that its results are still available to download, and unknown means only that this API is older than the state the service reported.
	State InvestigationJobState `json:"state"`
	// A short description of what the investigation looked into. Omitted when the investigation has no title yet.
	Title *string `json:"title,omitempty"`
}

func (i InvestigationJob) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InvestigationJob) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InvestigationJob) GetCompleteTime() *time.Time {
	if i == nil {
		return nil
	}
	return i.CompleteTime
}

func (i *InvestigationJob) GetCreateTime() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreateTime
}

func (i *InvestigationJob) GetExpireTime() *time.Time {
	if i == nil {
		return nil
	}
	return i.ExpireTime
}

func (i *InvestigationJob) GetJobID() string {
	if i == nil {
		return ""
	}
	return i.JobID
}

func (i *InvestigationJob) GetState() InvestigationJobState {
	if i == nil {
		return InvestigationJobState("")
	}
	return i.State
}

func (i *InvestigationJob) GetTitle() *string {
	if i == nil {
		return nil
	}
	return i.Title
}
