// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TransportProtocol string

const (
	TransportProtocolUnknown TransportProtocol = ""
	TransportProtocolTCP     TransportProtocol = "tcp"
	TransportProtocolUDP     TransportProtocol = "udp"
	TransportProtocolIcmp    TransportProtocol = "icmp"
	TransportProtocolQuic    TransportProtocol = "quic"
)

func (e TransportProtocol) ToPointer() *TransportProtocol {
	return &e
}
func (e *TransportProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "tcp":
		fallthrough
	case "udp":
		fallthrough
	case "icmp":
		fallthrough
	case "quic":
		*e = TransportProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TransportProtocol: %v", v)
	}
}

type MatchedService struct {
	Port              *int               `json:"port,omitempty"`
	Protocol          *string            `json:"protocol,omitempty"`
	TransportProtocol *TransportProtocol `json:"transport_protocol,omitempty"`
}

func (m *MatchedService) GetPort() *int {
	if m == nil {
		return nil
	}
	return m.Port
}

func (m *MatchedService) GetProtocol() *string {
	if m == nil {
		return nil
	}
	return m.Protocol
}

func (m *MatchedService) GetTransportProtocol() *TransportProtocol {
	if m == nil {
		return nil
	}
	return m.TransportProtocol
}
