// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MemberModuleRole struct {
	// The module identifier, for example platform-search.
	Module string `json:"module"`
	// The display name of the module.
	ModuleDisplayName string `json:"module_display_name"`
	// The role the user holds in the module, for example gs_analyst.
	Role string `json:"role"`
	// The display name of the role.
	RoleDisplayName string `json:"role_display_name"`
}

func (m *MemberModuleRole) GetModule() string {
	if m == nil {
		return ""
	}
	return m.Module
}

func (m *MemberModuleRole) GetModuleDisplayName() string {
	if m == nil {
		return ""
	}
	return m.ModuleDisplayName
}

func (m *MemberModuleRole) GetRole() string {
	if m == nil {
		return ""
	}
	return m.Role
}

func (m *MemberModuleRole) GetRoleDisplayName() string {
	if m == nil {
		return ""
	}
	return m.RoleDisplayName
}
