// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ModuleRoleOption struct {
	// The display name of the role.
	DisplayName string `json:"display_name"`
	// The role identifier.
	Role string `json:"role"`
}

func (m *ModuleRoleOption) GetDisplayName() string {
	if m == nil {
		return ""
	}
	return m.DisplayName
}

func (m *ModuleRoleOption) GetRole() string {
	if m == nil {
		return ""
	}
	return m.Role
}
