// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrganizationModule struct {
	// The display name of the module.
	DisplayName string `json:"display_name"`
	// The module whose roles grant access to this module, for example platform-search. Present only for modules included with another module, which have no roles or seats of their own.
	IncludedWith *string `json:"included_with,omitempty"`
	// The module identifier.
	Module string `json:"module"`
	// The roles this module offers.
	Roles []ModuleRoleOption `json:"roles"`
	// The number of seats the organization may fill in this module. Absent when unlimited or when the module is included with another module.
	SeatLimit *int64 `json:"seat_limit,omitempty"`
	// The number of users currently assigned to this module. Absent when the module is included with another module.
	SeatsAssigned *int64 `json:"seats_assigned,omitempty"`
}

func (o *OrganizationModule) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}

func (o *OrganizationModule) GetIncludedWith() *string {
	if o == nil {
		return nil
	}
	return o.IncludedWith
}

func (o *OrganizationModule) GetModule() string {
	if o == nil {
		return ""
	}
	return o.Module
}

func (o *OrganizationModule) GetRoles() []ModuleRoleOption {
	if o == nil {
		return []ModuleRoleOption{}
	}
	return o.Roles
}

func (o *OrganizationModule) GetSeatLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.SeatLimit
}

func (o *OrganizationModule) GetSeatsAssigned() *int64 {
	if o == nil {
		return nil
	}
	return o.SeatsAssigned
}
