// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RawCertificateResponse struct {
	CertificateID string `json:"certificate_id"`
	Pem           string `json:"pem"`
}

func (o *RawCertificateResponse) GetCertificateID() string {
	if o == nil {
		return ""
	}
	return o.CertificateID
}

func (o *RawCertificateResponse) GetPem() string {
	if o == nil {
		return ""
	}
	return o.Pem
}
