// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseEnvelopeInvestigationUsage struct {
	Result *InvestigationUsage `json:"result,omitempty"`
}

func (r *ResponseEnvelopeInvestigationUsage) GetResult() *InvestigationUsage {
	if r == nil {
		return nil
	}
	return r.Result
}
