// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseEnvelopeListSearchConvertQueryResponse struct {
	Result []SearchConvertQueryResponse `json:"result,omitempty"`
}

func (o *ResponseEnvelopeListSearchConvertQueryResponse) GetResult() []SearchConvertQueryResponse {
	if o == nil {
		return nil
	}
	return o.Result
}
