// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseEnvelopeListRawCertificateResponse struct {
	Result []RawCertificateResponse `json:"result,omitempty"`
}

func (o *ResponseEnvelopeListRawCertificateResponse) GetResult() []RawCertificateResponse {
	if o == nil {
		return nil
	}
	return o.Result
}
