// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseEnvelopeInvestigationJob struct {
	Result *InvestigationJob `json:"result,omitempty"`
}

func (r *ResponseEnvelopeInvestigationJob) GetResult() *InvestigationJob {
	if r == nil {
		return nil
	}
	return r.Result
}
