// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseEnvelopeInvestigationJobsList struct {
	Result *InvestigationJobsList `json:"result,omitempty"`
}

func (r *ResponseEnvelopeInvestigationJobsList) GetResult() *InvestigationJobsList {
	if r == nil {
		return nil
	}
	return r.Result
}
