// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseEnvelopeCreatedInvestigationJob struct {
	Result *CreatedInvestigationJob `json:"result,omitempty"`
}

func (r *ResponseEnvelopeCreatedInvestigationJob) GetResult() *CreatedInvestigationJob {
	if r == nil {
		return nil
	}
	return r.Result
}
