// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseEnvelopeInvestigationFileUpload struct {
	Result *InvestigationFileUpload `json:"result,omitempty"`
}

func (r *ResponseEnvelopeInvestigationFileUpload) GetResult() *InvestigationFileUpload {
	if r == nil {
		return nil
	}
	return r.Result
}
