// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Screenshot struct {
	Handle *string `json:"handle,omitempty"`
}

func (o *Screenshot) GetHandle() *string {
	if o == nil {
		return nil
	}
	return o.Handle
}
