// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Screenshot struct {
	ExtractedText *string `json:"extracted_text,omitempty"`
	Handle        *string `json:"handle,omitempty"`
	Phash         *string `json:"phash,omitempty"`
}

func (s *Screenshot) GetExtractedText() *string {
	if s == nil {
		return nil
	}
	return s.ExtractedText
}

func (s *Screenshot) GetHandle() *string {
	if s == nil {
		return nil
	}
	return s.Handle
}

func (s *Screenshot) GetPhash() *string {
	if s == nil {
		return nil
	}
	return s.Phash
}
