// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SearchValueCountsInputBody struct {
	// Groups of field-value pairs to count matches for. Each group must target fields from the same nested object.
	AndCountConditions [][]FieldValuePair `json:"and_count_conditions"`
}

func (o *SearchValueCountsInputBody) GetAndCountConditions() [][]FieldValuePair {
	if o == nil {
		return nil
	}
	return o.AndCountConditions
}
