// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SearchConvertQueryInputBody struct {
	// A list of Censys Search Language queries to convert. Limited to 100 queries.
	Queries []string `json:"queries"`
}

func (o *SearchConvertQueryInputBody) GetQueries() []string {
	if o == nil {
		return nil
	}
	return o.Queries
}
