// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SearchQueryHit struct {
	CertificateV1 *CertificateAsset `json:"certificate_v1,omitempty"`
	HostV1        *HostAsset        `json:"host_v1,omitempty"`
	WebpropertyV1 *WebpropertyAsset `json:"webproperty_v1,omitempty"`
}

func (s *SearchQueryHit) GetCertificateV1() *CertificateAsset {
	if s == nil {
		return nil
	}
	return s.CertificateV1
}

func (s *SearchQueryHit) GetHostV1() *HostAsset {
	if s == nil {
		return nil
	}
	return s.HostV1
}

func (s *SearchQueryHit) GetWebpropertyV1() *WebpropertyAsset {
	if s == nil {
		return nil
	}
	return s.WebpropertyV1
}
