// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type SearchConvertQueryResponseTargets string

const (
	SearchConvertQueryResponseTargetsHost    SearchConvertQueryResponseTargets = "host"
	SearchConvertQueryResponseTargetsWeb     SearchConvertQueryResponseTargets = "web"
	SearchConvertQueryResponseTargetsCert    SearchConvertQueryResponseTargets = "cert"
	SearchConvertQueryResponseTargetsUnknown SearchConvertQueryResponseTargets = "unknown"
)

func (e SearchConvertQueryResponseTargets) ToPointer() *SearchConvertQueryResponseTargets {
	return &e
}
func (e *SearchConvertQueryResponseTargets) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "host":
		fallthrough
	case "web":
		fallthrough
	case "cert":
		fallthrough
	case "unknown":
		*e = SearchConvertQueryResponseTargets(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SearchConvertQueryResponseTargets: %v", v)
	}
}

type SearchConvertQueryResponse struct {
	// Alternative queries that may be used. For example, a query that includes web results in addition to host results.
	AlternativeQueries []AlternativeQuery `json:"alternative_queries,omitempty"`
	// Comments about the query conversion.
	Comments []string `json:"comments,omitempty"`
	// The original query, converted to CenQL syntax. This may be empty if unable to translate the query.
	ConvertedQuery *string `json:"converted_query,omitempty"`
	// The error messages if the query could not be converted.
	Errors []ConvertQueryError `json:"errors"`
	// The original Censys Search Language query.
	OriginalQuery string `json:"original_query"`
	// The types of Platform data records (host, cert, and web) that can be targeted by the converted query. Note: Does not include targets that could be returned due to full-document search. This may be empty if the query is a match-all for full-document search query.
	Targets []SearchConvertQueryResponseTargets `json:"targets"`
}

func (o *SearchConvertQueryResponse) GetAlternativeQueries() []AlternativeQuery {
	if o == nil {
		return nil
	}
	return o.AlternativeQueries
}

func (o *SearchConvertQueryResponse) GetComments() []string {
	if o == nil {
		return nil
	}
	return o.Comments
}

func (o *SearchConvertQueryResponse) GetConvertedQuery() *string {
	if o == nil {
		return nil
	}
	return o.ConvertedQuery
}

func (o *SearchConvertQueryResponse) GetErrors() []ConvertQueryError {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *SearchConvertQueryResponse) GetOriginalQuery() string {
	if o == nil {
		return ""
	}
	return o.OriginalQuery
}

func (o *SearchConvertQueryResponse) GetTargets() []SearchConvertQueryResponseTargets {
	if o == nil {
		return nil
	}
	return o.Targets
}
