// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SearchValueCountsInputBody struct {
	// Conditions that are AND-ed together to determine what to count
	AndCountConditions [][]FieldValuePair `json:"and_count_conditions"`
}

func (o *SearchValueCountsInputBody) GetAndCountConditions() [][]FieldValuePair {
	if o == nil {
		return nil
	}
	return o.AndCountConditions
}
