// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SearchQueryInputBody struct {
	// specify fields to return in response and ignore others
	Fields []string `json:"fields,omitempty"`
	// amount of results to return per page
	PageSize *int64 `json:"page_size,omitempty"`
	// page token for the requested page of search results
	PageToken *string `json:"page_token,omitempty"`
	// CenQL query string to search upon
	Query string `json:"query"`
}

func (s *SearchQueryInputBody) GetFields() []string {
	if s == nil {
		return nil
	}
	return s.Fields
}

func (s *SearchQueryInputBody) GetPageSize() *int64 {
	if s == nil {
		return nil
	}
	return s.PageSize
}

func (s *SearchQueryInputBody) GetPageToken() *string {
	if s == nil {
		return nil
	}
	return s.PageToken
}

func (s *SearchQueryInputBody) GetQuery() string {
	if s == nil {
		return ""
	}
	return s.Query
}
