// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SearchAggregateInputBody struct {
	// Specify field to aggregate by.
	Field string `json:"field"`
	// Number of buckets to split results into.
	NumberOfBuckets int64 `json:"number_of_buckets"`
	// CenQL query string to search upon.
	Query string `json:"query"`
}

func (o *SearchAggregateInputBody) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *SearchAggregateInputBody) GetNumberOfBuckets() int64 {
	if o == nil {
		return 0
	}
	return o.NumberOfBuckets
}

func (o *SearchAggregateInputBody) GetQuery() string {
	if o == nil {
		return ""
	}
	return o.Query
}
