// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SearchValueCountsInputBody struct {
	// Groups of field-value pairs to count matches for.
	AndCountConditions []CountCondition `json:"and_count_conditions"`
}

func (o *SearchValueCountsInputBody) GetAndCountConditions() []CountCondition {
	if o == nil {
		return nil
	}
	return o.AndCountConditions
}
