// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ServicesOnHostResponse struct {
	NextPageToken string               `json:"NextPageToken"`
	Ranges        []ServiceOnHostRange `json:"Ranges"`
}

func (s *ServicesOnHostResponse) GetNextPageToken() string {
	if s == nil {
		return ""
	}
	return s.NextPageToken
}

func (s *ServicesOnHostResponse) GetRanges() []ServiceOnHostRange {
	if s == nil {
		return nil
	}
	return s.Ranges
}
