// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ServiceScanTransportProtocol string

const (
	ServiceScanTransportProtocolUnknown ServiceScanTransportProtocol = ""
	ServiceScanTransportProtocolTCP     ServiceScanTransportProtocol = "tcp"
	ServiceScanTransportProtocolUDP     ServiceScanTransportProtocol = "udp"
	ServiceScanTransportProtocolIcmp    ServiceScanTransportProtocol = "icmp"
	ServiceScanTransportProtocolQuic    ServiceScanTransportProtocol = "quic"
)

func (e ServiceScanTransportProtocol) ToPointer() *ServiceScanTransportProtocol {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ServiceScanTransportProtocol) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "tcp", "udp", "icmp", "quic":
			return true
		}
	}
	return false
}

type ServiceScan struct {
	Activemq                 *Activemq                     `json:"activemq,omitempty"`
	Amqp                     *Amqp                         `json:"amqp,omitempty"`
	AnyConnect               *AnyConnect                   `json:"any_connect,omitempty"`
	AsteriskManagerInterface *AsteriskManagerInterface     `json:"asterisk_manager_interface,omitempty"`
	Bacnet                   *Bacnet                       `json:"bacnet,omitempty"`
	Banner                   *string                       `json:"banner,omitempty"`
	BannerHashSha256         *string                       `json:"banner_hash_sha256,omitempty"`
	CheckpointTopology       *CheckpointTopology           `json:"checkpoint_topology,omitempty"`
	Chromecast               *Chromecast                   `json:"chromecast,omitempty"`
	CiscoIpsla               *CiscoIpsla                   `json:"cisco_ipsla,omitempty"`
	Cmore                    *Cmore                        `json:"cmore,omitempty"`
	Coap                     *Coap                         `json:"coap,omitempty"`
	CrestronCp3              *CrestronCp3                  `json:"crestron_cp3,omitempty"`
	CrestronDinAp2           *CrestronDinAp2               `json:"crestron_din_ap2,omitempty"`
	Cwmp                     *Cwmp                         `json:"cwmp,omitempty"`
	Darkcomet                *Darkcomet                    `json:"darkcomet,omitempty"`
	Darkgate                 *Darkgate                     `json:"darkgate,omitempty"`
	Dcerpc                   *Dcerpc                       `json:"dcerpc,omitempty"`
	Dhcpdiscover             *Dhcpdiscover                 `json:"dhcpdiscover,omitempty"`
	Dnp3                     *Dnp3                         `json:"dnp3,omitempty"`
	DNS                      *DNS                          `json:"dns,omitempty"`
	Dtls                     *Dtls                         `json:"dtls,omitempty"`
	DvrIP                    *DvrIP                        `json:"dvr_ip,omitempty"`
	Eip                      *Eip                          `json:"eip,omitempty"`
	ElfFile                  *ElfFile                      `json:"elf_file,omitempty"`
	Epmd                     *Epmd                         `json:"epmd,omitempty"`
	Etcd                     *Etcd                         `json:"etcd,omitempty"`
	Ethereum                 *Ethereum                     `json:"ethereum,omitempty"`
	Fox                      *Fox                          `json:"fox,omitempty"`
	Ftp                      *Ftp                          `json:"ftp,omitempty"`
	Gearman                  *Gearman                      `json:"gearman,omitempty"`
	Hajime                   *Hajime                       `json:"hajime,omitempty"`
	HidVertx                 *HidVertx                     `json:"hid_vertx,omitempty"`
	Hikvision                *Hikvision                    `json:"hikvision,omitempty"`
	Ibmnje                   *Ibmnje                       `json:"ibmnje,omitempty"`
	Ike                      *Ike                          `json:"ike,omitempty"`
	Imap                     *Imap                         `json:"imap,omitempty"`
	Iota                     *Iota                         `json:"iota,omitempty"`
	IP                       *string                       `json:"ip,omitempty"`
	Ipmi                     *Ipmi                         `json:"ipmi,omitempty"`
	Ipp                      *Ipp                          `json:"ipp,omitempty"`
	IsSuccess                *bool                         `json:"is_success,omitempty"`
	Iscsi                    *Iscsi                        `json:"iscsi,omitempty"`
	Krpc                     *Krpc                         `json:"krpc,omitempty"`
	L2tp                     *L2Tp                         `json:"l2tp,omitempty"`
	Ldap                     *Ldap                         `json:"ldap,omitempty"`
	Lpd                      *Lpd                          `json:"lpd,omitempty"`
	Mdns                     *Mdns                         `json:"mdns,omitempty"`
	Memcached                *Memcached                    `json:"memcached,omitempty"`
	MikrotikWinbox           *MikrotikWinbox               `json:"mikrotik_winbox,omitempty"`
	Minecraft                *Minecraft                    `json:"minecraft,omitempty"`
	Mms                      *Mms                          `json:"mms,omitempty"`
	Modbus                   *Modbus                       `json:"modbus,omitempty"`
	MoneroP2p                *MoneroP2P                    `json:"monero_p2p,omitempty"`
	Mongodb                  *Mongodb                      `json:"mongodb,omitempty"`
	Mqtt                     *Mqtt                         `json:"mqtt,omitempty"`
	Mssql                    *Mssql                        `json:"mssql,omitempty"`
	Murmur                   *Murmur                       `json:"murmur,omitempty"`
	Mysql                    *Mysql                        `json:"mysql,omitempty"`
	NatsIo                   *NatsIo                       `json:"nats_io,omitempty"`
	Nbd                      *Nbd                          `json:"nbd,omitempty"`
	NfsMountd                *NfsMountd                    `json:"nfs_mountd,omitempty"`
	Nmea                     *Nmea                         `json:"nmea,omitempty"`
	Ntp                      *Ntp                          `json:"ntp,omitempty"`
	Ntrip                    *Ntrip                        `json:"ntrip,omitempty"`
	Onc                      *Onc                          `json:"onc,omitempty"`
	Onvif                    *Onvif                        `json:"onvif,omitempty"`
	OpcUa                    *OpcUa                        `json:"opc_ua,omitempty"`
	Openvpn                  *Openvpn                      `json:"openvpn,omitempty"`
	OpenvpnMgmt              *OpenvpnMgmt                  `json:"openvpn_mgmt,omitempty"`
	Oracle                   *Oracle                       `json:"oracle,omitempty"`
	PcAnywhere               *PcAnywhere                   `json:"pc_anywhere,omitempty"`
	Pgbouncer                *Pgbouncer                    `json:"pgbouncer,omitempty"`
	Pop3                     *Pop3                         `json:"pop3,omitempty"`
	Port                     *int                          `json:"port,omitempty"`
	Portmap                  *Portmap                      `json:"portmap,omitempty"`
	Postgres                 *Postgres                     `json:"postgres,omitempty"`
	Pptp                     *Pptp                         `json:"pptp,omitempty"`
	ProfinetCm               *ProfinetCm                   `json:"profinet_cm,omitempty"`
	Protocol                 *string                       `json:"protocol,omitempty"`
	Rdate                    *Rdate                        `json:"rdate,omitempty"`
	Rdp                      *Rdp                          `json:"rdp,omitempty"`
	Realport                 *Realport                     `json:"realport,omitempty"`
	Redis                    *Redis                        `json:"redis,omitempty"`
	Redline                  *Redline                      `json:"redline,omitempty"`
	RedlionCrimson           *RedlionCrimson               `json:"redlion_crimson,omitempty"`
	RepresentativeInfo       *RepresentativeInfo           `json:"representative_info,omitempty"`
	Rifatron                 *Rifatron                     `json:"rifatron,omitempty"`
	Ripple                   *Ripple                       `json:"ripple,omitempty"`
	Rlogin                   *Rlogin                       `json:"rlogin,omitempty"`
	Rocketmq                 *Rocketmq                     `json:"rocketmq,omitempty"`
	Rtsp                     *Rtsp                         `json:"rtsp,omitempty"`
	S7                       *S7                           `json:"s7,omitempty"`
	SapRouter                *SapRouter                    `json:"sap_router,omitempty"`
	ScanTime                 *string                       `json:"scan_time,omitempty"`
	Scpi                     *Scpi                         `json:"scpi,omitempty"`
	Screenshots              []Screenshot                  `json:"screenshots,omitempty"`
	Ser2net                  *Ser2Net                      `json:"ser2net,omitempty"`
	SevenDaysToDie           *SevenDaysToDie               `json:"seven_days_to_die,omitempty"`
	Sip                      *Sip                          `json:"sip,omitempty"`
	Skinny                   *Skinny                       `json:"skinny,omitempty"`
	Smb                      *Smb                          `json:"smb,omitempty"`
	SMTP                     *SMTP                         `json:"smtp,omitempty"`
	Snmp                     *Snmp                         `json:"snmp,omitempty"`
	Socks                    *Socks                        `json:"socks,omitempty"`
	Spice                    *Spice                        `json:"spice,omitempty"`
	Ssdp                     *Ssdp                         `json:"ssdp,omitempty"`
	SSH                      *SSH                          `json:"ssh,omitempty"`
	Steam                    *Steam                        `json:"steam,omitempty"`
	TacacsPlus               *TacacsPlus                   `json:"tacacs_plus,omitempty"`
	TeamViewer               *TeamViewer                   `json:"team_viewer,omitempty"`
	Telnet                   *Telnet                       `json:"telnet,omitempty"`
	Tibia                    *Tibia                        `json:"tibia,omitempty"`
	TLS                      *TLS                          `json:"tls,omitempty"`
	TplinkKasa               *TplinkKasa                   `json:"tplink_kasa,omitempty"`
	TransportProtocol        *ServiceScanTransportProtocol `json:"transport_protocol,omitempty"`
	UnitronicsPcom           *UnitronicsPcom               `json:"unitronics_pcom,omitempty"`
	Upnp                     *Upnp                         `json:"upnp,omitempty"`
	Ventrilo                 *Ventrilo                     `json:"ventrilo,omitempty"`
	Vnc                      *Vnc                          `json:"vnc,omitempty"`
	WeblogicT3               *WeblogicT3                   `json:"weblogic_t3,omitempty"`
	Winrm                    *Winrm                        `json:"winrm,omitempty"`
	WsDiscovery              *WsDiscovery                  `json:"ws_discovery,omitempty"`
	X11                      *X11                          `json:"x11,omitempty"`
	Zeromq                   *Zeromq                       `json:"zeromq,omitempty"`
}

func (s *ServiceScan) GetActivemq() *Activemq {
	if s == nil {
		return nil
	}
	return s.Activemq
}

func (s *ServiceScan) GetAmqp() *Amqp {
	if s == nil {
		return nil
	}
	return s.Amqp
}

func (s *ServiceScan) GetAnyConnect() *AnyConnect {
	if s == nil {
		return nil
	}
	return s.AnyConnect
}

func (s *ServiceScan) GetAsteriskManagerInterface() *AsteriskManagerInterface {
	if s == nil {
		return nil
	}
	return s.AsteriskManagerInterface
}

func (s *ServiceScan) GetBacnet() *Bacnet {
	if s == nil {
		return nil
	}
	return s.Bacnet
}

func (s *ServiceScan) GetBanner() *string {
	if s == nil {
		return nil
	}
	return s.Banner
}

func (s *ServiceScan) GetBannerHashSha256() *string {
	if s == nil {
		return nil
	}
	return s.BannerHashSha256
}

func (s *ServiceScan) GetCheckpointTopology() *CheckpointTopology {
	if s == nil {
		return nil
	}
	return s.CheckpointTopology
}

func (s *ServiceScan) GetChromecast() *Chromecast {
	if s == nil {
		return nil
	}
	return s.Chromecast
}

func (s *ServiceScan) GetCiscoIpsla() *CiscoIpsla {
	if s == nil {
		return nil
	}
	return s.CiscoIpsla
}

func (s *ServiceScan) GetCmore() *Cmore {
	if s == nil {
		return nil
	}
	return s.Cmore
}

func (s *ServiceScan) GetCoap() *Coap {
	if s == nil {
		return nil
	}
	return s.Coap
}

func (s *ServiceScan) GetCrestronCp3() *CrestronCp3 {
	if s == nil {
		return nil
	}
	return s.CrestronCp3
}

func (s *ServiceScan) GetCrestronDinAp2() *CrestronDinAp2 {
	if s == nil {
		return nil
	}
	return s.CrestronDinAp2
}

func (s *ServiceScan) GetCwmp() *Cwmp {
	if s == nil {
		return nil
	}
	return s.Cwmp
}

func (s *ServiceScan) GetDarkcomet() *Darkcomet {
	if s == nil {
		return nil
	}
	return s.Darkcomet
}

func (s *ServiceScan) GetDarkgate() *Darkgate {
	if s == nil {
		return nil
	}
	return s.Darkgate
}

func (s *ServiceScan) GetDcerpc() *Dcerpc {
	if s == nil {
		return nil
	}
	return s.Dcerpc
}

func (s *ServiceScan) GetDhcpdiscover() *Dhcpdiscover {
	if s == nil {
		return nil
	}
	return s.Dhcpdiscover
}

func (s *ServiceScan) GetDnp3() *Dnp3 {
	if s == nil {
		return nil
	}
	return s.Dnp3
}

func (s *ServiceScan) GetDNS() *DNS {
	if s == nil {
		return nil
	}
	return s.DNS
}

func (s *ServiceScan) GetDtls() *Dtls {
	if s == nil {
		return nil
	}
	return s.Dtls
}

func (s *ServiceScan) GetDvrIP() *DvrIP {
	if s == nil {
		return nil
	}
	return s.DvrIP
}

func (s *ServiceScan) GetEip() *Eip {
	if s == nil {
		return nil
	}
	return s.Eip
}

func (s *ServiceScan) GetElfFile() *ElfFile {
	if s == nil {
		return nil
	}
	return s.ElfFile
}

func (s *ServiceScan) GetEpmd() *Epmd {
	if s == nil {
		return nil
	}
	return s.Epmd
}

func (s *ServiceScan) GetEtcd() *Etcd {
	if s == nil {
		return nil
	}
	return s.Etcd
}

func (s *ServiceScan) GetEthereum() *Ethereum {
	if s == nil {
		return nil
	}
	return s.Ethereum
}

func (s *ServiceScan) GetFox() *Fox {
	if s == nil {
		return nil
	}
	return s.Fox
}

func (s *ServiceScan) GetFtp() *Ftp {
	if s == nil {
		return nil
	}
	return s.Ftp
}

func (s *ServiceScan) GetGearman() *Gearman {
	if s == nil {
		return nil
	}
	return s.Gearman
}

func (s *ServiceScan) GetHajime() *Hajime {
	if s == nil {
		return nil
	}
	return s.Hajime
}

func (s *ServiceScan) GetHidVertx() *HidVertx {
	if s == nil {
		return nil
	}
	return s.HidVertx
}

func (s *ServiceScan) GetHikvision() *Hikvision {
	if s == nil {
		return nil
	}
	return s.Hikvision
}

func (s *ServiceScan) GetIbmnje() *Ibmnje {
	if s == nil {
		return nil
	}
	return s.Ibmnje
}

func (s *ServiceScan) GetIke() *Ike {
	if s == nil {
		return nil
	}
	return s.Ike
}

func (s *ServiceScan) GetImap() *Imap {
	if s == nil {
		return nil
	}
	return s.Imap
}

func (s *ServiceScan) GetIota() *Iota {
	if s == nil {
		return nil
	}
	return s.Iota
}

func (s *ServiceScan) GetIP() *string {
	if s == nil {
		return nil
	}
	return s.IP
}

func (s *ServiceScan) GetIpmi() *Ipmi {
	if s == nil {
		return nil
	}
	return s.Ipmi
}

func (s *ServiceScan) GetIpp() *Ipp {
	if s == nil {
		return nil
	}
	return s.Ipp
}

func (s *ServiceScan) GetIsSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.IsSuccess
}

func (s *ServiceScan) GetIscsi() *Iscsi {
	if s == nil {
		return nil
	}
	return s.Iscsi
}

func (s *ServiceScan) GetKrpc() *Krpc {
	if s == nil {
		return nil
	}
	return s.Krpc
}

func (s *ServiceScan) GetL2tp() *L2Tp {
	if s == nil {
		return nil
	}
	return s.L2tp
}

func (s *ServiceScan) GetLdap() *Ldap {
	if s == nil {
		return nil
	}
	return s.Ldap
}

func (s *ServiceScan) GetLpd() *Lpd {
	if s == nil {
		return nil
	}
	return s.Lpd
}

func (s *ServiceScan) GetMdns() *Mdns {
	if s == nil {
		return nil
	}
	return s.Mdns
}

func (s *ServiceScan) GetMemcached() *Memcached {
	if s == nil {
		return nil
	}
	return s.Memcached
}

func (s *ServiceScan) GetMikrotikWinbox() *MikrotikWinbox {
	if s == nil {
		return nil
	}
	return s.MikrotikWinbox
}

func (s *ServiceScan) GetMinecraft() *Minecraft {
	if s == nil {
		return nil
	}
	return s.Minecraft
}

func (s *ServiceScan) GetMms() *Mms {
	if s == nil {
		return nil
	}
	return s.Mms
}

func (s *ServiceScan) GetModbus() *Modbus {
	if s == nil {
		return nil
	}
	return s.Modbus
}

func (s *ServiceScan) GetMoneroP2p() *MoneroP2P {
	if s == nil {
		return nil
	}
	return s.MoneroP2p
}

func (s *ServiceScan) GetMongodb() *Mongodb {
	if s == nil {
		return nil
	}
	return s.Mongodb
}

func (s *ServiceScan) GetMqtt() *Mqtt {
	if s == nil {
		return nil
	}
	return s.Mqtt
}

func (s *ServiceScan) GetMssql() *Mssql {
	if s == nil {
		return nil
	}
	return s.Mssql
}

func (s *ServiceScan) GetMurmur() *Murmur {
	if s == nil {
		return nil
	}
	return s.Murmur
}

func (s *ServiceScan) GetMysql() *Mysql {
	if s == nil {
		return nil
	}
	return s.Mysql
}

func (s *ServiceScan) GetNatsIo() *NatsIo {
	if s == nil {
		return nil
	}
	return s.NatsIo
}

func (s *ServiceScan) GetNbd() *Nbd {
	if s == nil {
		return nil
	}
	return s.Nbd
}

func (s *ServiceScan) GetNfsMountd() *NfsMountd {
	if s == nil {
		return nil
	}
	return s.NfsMountd
}

func (s *ServiceScan) GetNmea() *Nmea {
	if s == nil {
		return nil
	}
	return s.Nmea
}

func (s *ServiceScan) GetNtp() *Ntp {
	if s == nil {
		return nil
	}
	return s.Ntp
}

func (s *ServiceScan) GetNtrip() *Ntrip {
	if s == nil {
		return nil
	}
	return s.Ntrip
}

func (s *ServiceScan) GetOnc() *Onc {
	if s == nil {
		return nil
	}
	return s.Onc
}

func (s *ServiceScan) GetOnvif() *Onvif {
	if s == nil {
		return nil
	}
	return s.Onvif
}

func (s *ServiceScan) GetOpcUa() *OpcUa {
	if s == nil {
		return nil
	}
	return s.OpcUa
}

func (s *ServiceScan) GetOpenvpn() *Openvpn {
	if s == nil {
		return nil
	}
	return s.Openvpn
}

func (s *ServiceScan) GetOpenvpnMgmt() *OpenvpnMgmt {
	if s == nil {
		return nil
	}
	return s.OpenvpnMgmt
}

func (s *ServiceScan) GetOracle() *Oracle {
	if s == nil {
		return nil
	}
	return s.Oracle
}

func (s *ServiceScan) GetPcAnywhere() *PcAnywhere {
	if s == nil {
		return nil
	}
	return s.PcAnywhere
}

func (s *ServiceScan) GetPgbouncer() *Pgbouncer {
	if s == nil {
		return nil
	}
	return s.Pgbouncer
}

func (s *ServiceScan) GetPop3() *Pop3 {
	if s == nil {
		return nil
	}
	return s.Pop3
}

func (s *ServiceScan) GetPort() *int {
	if s == nil {
		return nil
	}
	return s.Port
}

func (s *ServiceScan) GetPortmap() *Portmap {
	if s == nil {
		return nil
	}
	return s.Portmap
}

func (s *ServiceScan) GetPostgres() *Postgres {
	if s == nil {
		return nil
	}
	return s.Postgres
}

func (s *ServiceScan) GetPptp() *Pptp {
	if s == nil {
		return nil
	}
	return s.Pptp
}

func (s *ServiceScan) GetProfinetCm() *ProfinetCm {
	if s == nil {
		return nil
	}
	return s.ProfinetCm
}

func (s *ServiceScan) GetProtocol() *string {
	if s == nil {
		return nil
	}
	return s.Protocol
}

func (s *ServiceScan) GetRdate() *Rdate {
	if s == nil {
		return nil
	}
	return s.Rdate
}

func (s *ServiceScan) GetRdp() *Rdp {
	if s == nil {
		return nil
	}
	return s.Rdp
}

func (s *ServiceScan) GetRealport() *Realport {
	if s == nil {
		return nil
	}
	return s.Realport
}

func (s *ServiceScan) GetRedis() *Redis {
	if s == nil {
		return nil
	}
	return s.Redis
}

func (s *ServiceScan) GetRedline() *Redline {
	if s == nil {
		return nil
	}
	return s.Redline
}

func (s *ServiceScan) GetRedlionCrimson() *RedlionCrimson {
	if s == nil {
		return nil
	}
	return s.RedlionCrimson
}

func (s *ServiceScan) GetRepresentativeInfo() *RepresentativeInfo {
	if s == nil {
		return nil
	}
	return s.RepresentativeInfo
}

func (s *ServiceScan) GetRifatron() *Rifatron {
	if s == nil {
		return nil
	}
	return s.Rifatron
}

func (s *ServiceScan) GetRipple() *Ripple {
	if s == nil {
		return nil
	}
	return s.Ripple
}

func (s *ServiceScan) GetRlogin() *Rlogin {
	if s == nil {
		return nil
	}
	return s.Rlogin
}

func (s *ServiceScan) GetRocketmq() *Rocketmq {
	if s == nil {
		return nil
	}
	return s.Rocketmq
}

func (s *ServiceScan) GetRtsp() *Rtsp {
	if s == nil {
		return nil
	}
	return s.Rtsp
}

func (s *ServiceScan) GetS7() *S7 {
	if s == nil {
		return nil
	}
	return s.S7
}

func (s *ServiceScan) GetSapRouter() *SapRouter {
	if s == nil {
		return nil
	}
	return s.SapRouter
}

func (s *ServiceScan) GetScanTime() *string {
	if s == nil {
		return nil
	}
	return s.ScanTime
}

func (s *ServiceScan) GetScpi() *Scpi {
	if s == nil {
		return nil
	}
	return s.Scpi
}

func (s *ServiceScan) GetScreenshots() []Screenshot {
	if s == nil {
		return nil
	}
	return s.Screenshots
}

func (s *ServiceScan) GetSer2net() *Ser2Net {
	if s == nil {
		return nil
	}
	return s.Ser2net
}

func (s *ServiceScan) GetSevenDaysToDie() *SevenDaysToDie {
	if s == nil {
		return nil
	}
	return s.SevenDaysToDie
}

func (s *ServiceScan) GetSip() *Sip {
	if s == nil {
		return nil
	}
	return s.Sip
}

func (s *ServiceScan) GetSkinny() *Skinny {
	if s == nil {
		return nil
	}
	return s.Skinny
}

func (s *ServiceScan) GetSmb() *Smb {
	if s == nil {
		return nil
	}
	return s.Smb
}

func (s *ServiceScan) GetSMTP() *SMTP {
	if s == nil {
		return nil
	}
	return s.SMTP
}

func (s *ServiceScan) GetSnmp() *Snmp {
	if s == nil {
		return nil
	}
	return s.Snmp
}

func (s *ServiceScan) GetSocks() *Socks {
	if s == nil {
		return nil
	}
	return s.Socks
}

func (s *ServiceScan) GetSpice() *Spice {
	if s == nil {
		return nil
	}
	return s.Spice
}

func (s *ServiceScan) GetSsdp() *Ssdp {
	if s == nil {
		return nil
	}
	return s.Ssdp
}

func (s *ServiceScan) GetSSH() *SSH {
	if s == nil {
		return nil
	}
	return s.SSH
}

func (s *ServiceScan) GetSteam() *Steam {
	if s == nil {
		return nil
	}
	return s.Steam
}

func (s *ServiceScan) GetTacacsPlus() *TacacsPlus {
	if s == nil {
		return nil
	}
	return s.TacacsPlus
}

func (s *ServiceScan) GetTeamViewer() *TeamViewer {
	if s == nil {
		return nil
	}
	return s.TeamViewer
}

func (s *ServiceScan) GetTelnet() *Telnet {
	if s == nil {
		return nil
	}
	return s.Telnet
}

func (s *ServiceScan) GetTibia() *Tibia {
	if s == nil {
		return nil
	}
	return s.Tibia
}

func (s *ServiceScan) GetTLS() *TLS {
	if s == nil {
		return nil
	}
	return s.TLS
}

func (s *ServiceScan) GetTplinkKasa() *TplinkKasa {
	if s == nil {
		return nil
	}
	return s.TplinkKasa
}

func (s *ServiceScan) GetTransportProtocol() *ServiceScanTransportProtocol {
	if s == nil {
		return nil
	}
	return s.TransportProtocol
}

func (s *ServiceScan) GetUnitronicsPcom() *UnitronicsPcom {
	if s == nil {
		return nil
	}
	return s.UnitronicsPcom
}

func (s *ServiceScan) GetUpnp() *Upnp {
	if s == nil {
		return nil
	}
	return s.Upnp
}

func (s *ServiceScan) GetVentrilo() *Ventrilo {
	if s == nil {
		return nil
	}
	return s.Ventrilo
}

func (s *ServiceScan) GetVnc() *Vnc {
	if s == nil {
		return nil
	}
	return s.Vnc
}

func (s *ServiceScan) GetWeblogicT3() *WeblogicT3 {
	if s == nil {
		return nil
	}
	return s.WeblogicT3
}

func (s *ServiceScan) GetWinrm() *Winrm {
	if s == nil {
		return nil
	}
	return s.Winrm
}

func (s *ServiceScan) GetWsDiscovery() *WsDiscovery {
	if s == nil {
		return nil
	}
	return s.WsDiscovery
}

func (s *ServiceScan) GetX11() *X11 {
	if s == nil {
		return nil
	}
	return s.X11
}

func (s *ServiceScan) GetZeromq() *Zeromq {
	if s == nil {
		return nil
	}
	return s.Zeromq
}
