// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SetMemberModuleRoleInputBody struct {
	// The role to assign in this module, for example gs_analyst.
	Role string `json:"role"`
}

func (s *SetMemberModuleRoleInputBody) GetRole() string {
	if s == nil {
		return ""
	}
	return s.Role
}
