// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SourceUsageBreakdown struct {
	// The amount of credits consumed through the PlatformAPI.
	API int64 `json:"api"`
	// The amount of credits consumed through the Platform UI.
	UI int64 `json:"ui"`
}

func (s *SourceUsageBreakdown) GetAPI() int64 {
	if s == nil {
		return 0
	}
	return s.API
}

func (s *SourceUsageBreakdown) GetUI() int64 {
	if s == nil {
		return 0
	}
	return s.UI
}
