// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-sdk-go/internal/utils"
	"time"
)

// AssetType - The inferred type of the asset.
type AssetType string

const (
	AssetTypeHost        AssetType = "host"
	AssetTypeCertificate AssetType = "certificate"
	AssetTypeWebProperty AssetType = "web_property"
)

func (e AssetType) ToPointer() *AssetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AssetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "host", "certificate", "web_property":
			return true
		}
	}
	return false
}

type TagAssignment struct {
	// The identifier of the tagged asset (host IP, certificate SHA-256 fingerprint, or web property domain/IP:port).
	AssetID string `json:"asset_id"`
	// The inferred type of the asset.
	AssetType AssetType `json:"asset_type"`
	// RFC3339 timestamp when the assignment was created.
	CreatedAt time.Time `json:"created_at"`
	// The user ID of the user who created the assignment.
	CreatedBy string `json:"created_by"`
	// The unique ID of the assignment.
	ID string `json:"id"`
	// A direct URL to the asset in the Censys platform.
	PlatformRef string `json:"platform_ref"`
	// The ID of the tag.
	TagID string `json:"tag_id"`
}

func (t TagAssignment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TagAssignment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TagAssignment) GetAssetID() string {
	if t == nil {
		return ""
	}
	return t.AssetID
}

func (t *TagAssignment) GetAssetType() AssetType {
	if t == nil {
		return AssetType("")
	}
	return t.AssetType
}

func (t *TagAssignment) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TagAssignment) GetCreatedBy() string {
	if t == nil {
		return ""
	}
	return t.CreatedBy
}

func (t *TagAssignment) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TagAssignment) GetPlatformRef() string {
	if t == nil {
		return ""
	}
	return t.PlatformRef
}

func (t *TagAssignment) GetTagID() string {
	if t == nil {
		return ""
	}
	return t.TagID
}
