// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ThreatSource string

const (
	ThreatSourceUnknown    ThreatSource = ""
	ThreatSourceCensys     ThreatSource = "censys"
	ThreatSourceRecog      ThreatSource = "recog"
	ThreatSourceWappalyzer ThreatSource = "wappalyzer"
	ThreatSourceThirdParty ThreatSource = "third_party"
)

func (e ThreatSource) ToPointer() *ThreatSource {
	return &e
}
func (e *ThreatSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "censys":
		fallthrough
	case "recog":
		fallthrough
	case "wappalyzer":
		fallthrough
	case "third_party":
		*e = ThreatSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ThreatSource: %v", v)
	}
}

type Threat struct {
	Actors     []ThreatActor  `json:"actors,omitempty"`
	Confidence *float64       `json:"confidence,omitempty"`
	Details    *ThreatDetails `json:"details,omitempty"`
	Evidence   []Evidence     `json:"evidence,omitempty"`
	ID         *string        `json:"id,omitempty"`
	Malware    *ThreatMalware `json:"malware,omitempty"`
	Name       *string        `json:"name,omitempty"`
	Source     *ThreatSource  `json:"source,omitempty"`
	Tactic     []string       `json:"tactic,omitempty"`
	Type       []string       `json:"type,omitempty"`
}

func (t *Threat) GetActors() []ThreatActor {
	if t == nil {
		return nil
	}
	return t.Actors
}

func (t *Threat) GetConfidence() *float64 {
	if t == nil {
		return nil
	}
	return t.Confidence
}

func (t *Threat) GetDetails() *ThreatDetails {
	if t == nil {
		return nil
	}
	return t.Details
}

func (t *Threat) GetEvidence() []Evidence {
	if t == nil {
		return nil
	}
	return t.Evidence
}

func (t *Threat) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *Threat) GetMalware() *ThreatMalware {
	if t == nil {
		return nil
	}
	return t.Malware
}

func (t *Threat) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *Threat) GetSource() *ThreatSource {
	if t == nil {
		return nil
	}
	return t.Source
}

func (t *Threat) GetTactic() []string {
	if t == nil {
		return nil
	}
	return t.Tactic
}

func (t *Threat) GetType() []string {
	if t == nil {
		return nil
	}
	return t.Type
}
