// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VulnRiskSource string

const (
	VulnRiskSourceUnknown VulnRiskSource = ""
	VulnRiskSourceCensys  VulnRiskSource = "censys"
	VulnRiskSourceCve     VulnRiskSource = "cve"
)

func (e VulnRiskSource) ToPointer() *VulnRiskSource {
	return &e
}
func (e *VulnRiskSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "censys":
		fallthrough
	case "cve":
		*e = VulnRiskSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VulnRiskSource: %v", v)
	}
}

type VulnSeverity string

const (
	VulnSeverityUnknown  VulnSeverity = ""
	VulnSeverityLow      VulnSeverity = "low"
	VulnSeverityMedium   VulnSeverity = "medium"
	VulnSeverityHigh     VulnSeverity = "high"
	VulnSeverityCritical VulnSeverity = "critical"
)

func (e VulnSeverity) ToPointer() *VulnSeverity {
	return &e
}
func (e *VulnSeverity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "low":
		fallthrough
	case "medium":
		fallthrough
	case "high":
		fallthrough
	case "critical":
		*e = VulnSeverity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VulnSeverity: %v", v)
	}
}

type VulnSource string

const (
	VulnSourceUnknown    VulnSource = ""
	VulnSourceCensys     VulnSource = "censys"
	VulnSourceRecog      VulnSource = "recog"
	VulnSourceWappalyzer VulnSource = "wappalyzer"
	VulnSourceThirdParty VulnSource = "third_party"
)

func (e VulnSource) ToPointer() *VulnSource {
	return &e
}
func (e *VulnSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "censys":
		fallthrough
	case "recog":
		fallthrough
	case "wappalyzer":
		fallthrough
	case "third_party":
		*e = VulnSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VulnSource: %v", v)
	}
}

type Vuln struct {
	Confidence *float64        `json:"confidence,omitempty"`
	Cwes       []Cwe           `json:"cwes,omitempty"`
	Evidence   []Evidence      `json:"evidence,omitempty"`
	ID         *string         `json:"id,omitempty"`
	Kev        []Kev           `json:"kev,omitempty"`
	Metrics    *Metrics        `json:"metrics,omitempty"`
	Name       *string         `json:"name,omitempty"`
	RiskSource *VulnRiskSource `json:"risk_source,omitempty"`
	Severity   *VulnSeverity   `json:"severity,omitempty"`
	Source     *VulnSource     `json:"source,omitempty"`
	Year       *int            `json:"year,omitempty"`
}

func (v *Vuln) GetConfidence() *float64 {
	if v == nil {
		return nil
	}
	return v.Confidence
}

func (v *Vuln) GetCwes() []Cwe {
	if v == nil {
		return nil
	}
	return v.Cwes
}

func (v *Vuln) GetEvidence() []Evidence {
	if v == nil {
		return nil
	}
	return v.Evidence
}

func (v *Vuln) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *Vuln) GetKev() []Kev {
	if v == nil {
		return nil
	}
	return v.Kev
}

func (v *Vuln) GetMetrics() *Metrics {
	if v == nil {
		return nil
	}
	return v.Metrics
}

func (v *Vuln) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *Vuln) GetRiskSource() *VulnRiskSource {
	if v == nil {
		return nil
	}
	return v.RiskSource
}

func (v *Vuln) GetSeverity() *VulnSeverity {
	if v == nil {
		return nil
	}
	return v.Severity
}

func (v *Vuln) GetSource() *VulnSource {
	if v == nil {
		return nil
	}
	return v.Source
}

func (v *Vuln) GetYear() *int {
	if v == nil {
		return nil
	}
	return v.Year
}
